### ISSUE TITLE
Should path-resource replace resource paths or add to them?

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1038]
It's unclear if the `path-resource` parameter is intended to replace the resource paths (so the default paths no longer work) or just add to them.  SUSHI 2.3.0 assumes the latter (existing default paths continue to work).

We need to investigate to see how the IG Publisher behaves in order to determine the answer to this question.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/nested.20folders.20in.20.2Finput.2Fresources.2Fabc/near/274334692

**Comment by julianxcarter** [comment]
The IG Publisher doesn't log any errors/warnings when the path-resource parameter is used in an additive fashion. It'll also include resources from both locations in an IG when you use the parameter but also have resource in an already supported folder, so we've decided to have SUSHI allow this as well.
