### ISSUE TITLE
IG Pub warning about not finding value sets

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#105]
The IG Publisher is issuing "no value set found" warnings. I'm not sure whether this is benign or if there is an impact on the IG:
```
onGenerate:
No value set found at Extension.value[x]:valueCodeableConcept (url = 'AnatomicalOrientationVS')
No value set found at Extension.valueCodeableConcept (url = 'AnatomicalOrientationVS')
No value set found at Observation.value[x]:valueCodeableConcept (url = 'ConditionStatusTrendVS')
No value set found at Observation.value[x]:valueCodeableConcept (url = 'ConditionStatusTrendVS')
No value set found at Observation.valueCodeableConcept (url = 'ConditionStatusTrendVS')
No value set found at Observation.valueCodeableConcept (url = 'ConditionStatusTrendVS')
No value set found at Observation.value[x]:valueCodeableConcept (url = 'https://fhir.loinc.org/ValueSet/LL1971-2')
No value set found at Observation.value[x]:valueCodeableConcept (url = 'https://fhir.loinc.org/ValueSet/LL1971-2')
No value set found at Observation.valueCodeableConcept (url = 'https://fhir.loinc.org/ValueSet/LL1971-2')
No value set found at Observation.valueCodeableConcept (url = 'https://fhir.loinc.org/ValueSet/LL1971-2')
```

**Comment by cmoesel** [comment]
For `AnatomicalOrientationVS` and `ConditionStatusTrendVS`, these warnings are _true_.  As of now, those value sets are _not_ defined in `fsh-mcode` -- so the value set bindings are passed through as-is.

One thing we could do is start having SUSHI report it as an error if it detects a non-URL binding that can't be resolved to a URL (either via an Alias or a ValueSet definition in FSH).

**Comment by cmoesel** [comment]
As for the LOINC value sets, those aren't resolved because the URL is wrong.  Instead of:
```
https://fhir.loinc.org/ValueSet/LL1971-2
```
it should be:
```
http://loinc.org/vs/LL1971-2
```

See: http://hl7.org/fhir/R4/loinc.html#alist

**Comment by markkramerus** [comment]
Added the value sets and corrected some value set URLs.  Not a problem with SUSHI. 
 See https://github.com/standardhealth/fsh-mcode/pull/22
