### ISSUE TITLE
SUSHI does not allow for array Elements constrained via assignment rule to have additional elements 

### ISSUE THREAD

**Issue by julianxcarter** [FHIR/sushi#1055]
When an array element in a profile is constrained with an assignment rule, SUSHI does not allow for additional elements to be added to the array in an instance. E.g.  
```
Profile: ConditionProfile
Parent: Condition
* bodySite = http://snomed.info/sct#107008

Instance: MyCondition
InstanceOf: ConditionProfile
Usage: #example
* bodySite[1] = http://snomed.info/sct#108003
```
yields the following error:
```
error Cannot assign http://snomed.info/sct#108003 to this element; a different CodeableConcept is already assigned: {"coding":[{"code":"107008","system":"http://snomed.info/sct"}]}.
```

It stands to reason that unless the `(exactly)` keyword is included in the constraint, that additional elements should be allowed beyond the first element when constraints are made in this way.

FSHOnline link: https://fshschool.org/FSHOnline/#/share/3wXGHi7

**Comment by cmoesel** [comment]
Well... it's unfortunately not quite so simple.  There has been vigorous debate in the past on whether `pattern[x]` needs to match on _every_ element in the array or only one.  And the debate doesn't appear to have been resolved yet.  The IG Publisher renders it as if it's "at least one", but the IG Publisher's validator treats it as if it is "every one".

I've resurrected a Zulip thread where this was discussed in hopes that perhaps someone can fill us in on the current thinking: https://chat.fhir.org/#narrow/stream/179177-conformance/topic/pattern.5Bx.5D.20on.200.2E.2E*.20elements/near/277470333
