### ISSUE TITLE
Revisit approach to ordering resources in IG JSON

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1080]
See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/order.20of.20resources.20in.20the.20generated.20ig.2Ejson/near/261472343

**Comment by cmoesel** [comment]
Basically, SUSHI should do these things when generating the resource list in the IG:

1. Change default order from alpha by id to alpha by title
2. If the users lists ALL the resources in the sushi-config.yaml, then use that order instead
3. If the user provides their own groups, and every resource is assigned into a group, then maintain the order of the groups and resources when generating the resource list.

**Comment by jafeltra** [comment]
Completed in #1118
