### ISSUE TITLE
SUSHI should not include instances of custom resources in the IG

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1090]
The IG Publisher does not support custom resources.  SUSHI already suppresses custom resources from the generated IG JSON.  If an author creates an example of a custom resource, however, SUSHI _does_ still include that instance in the IG JSON.  This then causes problems in the IG Publisher (since it's referencing a custom resource).  SUSHI should probably suppress instances of custom resources too.

See: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/bad.20resource.20identity/near/282797466

Example FSH from issue reported on Zulip:
```
Resource: FormTemplate
Parent: Resource
Id: formtemplate
Title: "FHIR2 Form Template"
Description: "FHIR2 Form Template"
* template 1..1 BackboneElement "The root of the doc"
  * templateStatus 1..1 string "the template status"


Instance: FHIR2FormTemplateExample
InstanceOf: FormTemplate
Title: "Example : Questionnaire"
Description: "Example : Questionnaire"
Usage: #example
* template.templateStatus = "draft"
```

**Comment by guhanthuran** [comment]
Should this also include a warning that we aren't including these instances in the IG?
