### ISSUE TITLE
SUSHI should handle implicit type slicing

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1099]
If explicit type slices are present in a profile (e.g., `value[x].valueQuantity`), but that same profile does not explicitly specify a `slicing`, then when SUSHI tries to create an instance of the profile, it assumes there is a slicing and fails.  It's unclear if the lack of `slicing` is valid, but there are clearly existing profiles where this happens, so it would be nice for SUSHI to be able to handle this.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Error.20w.2F.20type.20slices.20missing.20discriminator/near/285666891

**Comment by ewoutkramer** [comment]
Our new validator suffers from the same problem. Sigh. It's time we get to the bottom of this.  Are you going to Baltimore? Seems like we need the major toolsmiths around a whiteboard.

**Comment by jafeltra** [comment]
I believe this issue is the same as #1408 and was fixed by #1434. If this is still an issue, feel free to reopen this issue.
