### ISSUE TITLE
Fsh-Sushi API not working with Webpack

### ISSUE THREAD

**Issue by alexgwalley** [FHIR/sushi#1105]
### The Issue
I am trying to pack the sushi with webpack and then run, however I get this error:

> webpack 5.73.0 compiled successfully in 8115 ms
> node:fs:208
>   let mode = stats[1];
>                   ^
> 

> TypeError: Cannot read properties of undefined (reading '1')
>     at isFileType (node:fs:208:19)
>     at Object.readFileSync (node:fs:456:16)
>     at C:\Users\awalley\SushiTesting\dist\extension.js:117148:19
>     at Array.map (<anonymous>)
>     at C:\Users\awalley\SushiTesting\dist\extension.js:117147:30
>     at Object.<anonymous> (C:\Users\awalley\SushiTesting\dist\extension.js:117152:2)   
>     at __webpack_require__ (C:\Users\awalley\SushiTesting\dist\extension.js:153931:42) 
>     at Object.<anonymous> (C:\Users\awalley\SushiTesting\dist\extension.js:98848:16)   
>     at __webpack_require__ (C:\Users\awalley\SushiTesting\dist\extension.js:153931:42) 
>     at Object.<anonymous> (C:\Users\awalley\SushiTesting\dist\extension.js:96599:25)

As you can see, webpack compiles it correctly, but my guess is that is is having a difficult time requiring/importing everything.
When debugging, it breaks at this file read:

![image](https://user-images.githubusercontent.com/10475866/174090420-18f16067-1d2e-4bc8-b817-a3e421d4ee26.png)

Looking for the 808 file descriptor in the dist/extension.js file, it brings me here:

![image](https://user-images.githubusercontent.com/10475866/174091507-8d6e3689-aac5-4b30-9f03-35883f3215c6.png)

**UglifyJS** is used by the **html-minifer** dependency as seen in node_modules/fsh-sushi/node-shrinkwrap.json

### To Reproduce
clone the repo: https://github.com/alexgwalley/SushiTesting.git, run npm i, then run the npm script "run". This packs and trys to run everything. When you debug the extension.js, if you check both boxes "caught Exceptions" and "uncaught exceptions" it should break here.

I am not quite sure how to fix this error, but any help is appreciated! Thanks

**Comment by alexgwalley** [comment]
If we change the dependency from html-minifier to html-minifier-terser, then everything works. It seems like html-minifier does not work with webpack v5 because of UglifyJS. I forked the repo and made this change (html-minifier is only used in fhirtypes/ElementDefinition.ts on line 1952).

Would you like me to submit a PR?

**Comment by cmoesel** [comment]
Hi @alexgwalley -- I apologize for the delay.  This one somehow got away from us!  We use SUSHI in FSH Online.  I think we got past this by setting up webpack to replace the uglify library with a null loader. See: https://github.com/FSHSchool/FSHOnline/blob/master/config-overrides.js

That said, I see that `html-minifier-terser` has about 10 million downloads a week (versus 3 million for `html-minifier`), so perhaps we should be considering `html-minifier-terser` anyway Please go ahead and submit a PR and we'll take a look.
