### ISSUE TITLE
FSHLogger ErrorsAndWarnings location type should be any

### ISSUE THREAD

**Issue by alexgwalley** [FHIR/sushi#1106]
In FSHLogger.ts, the current class of ErrorsAndWarnings is this:
```
export class ErrorsAndWarnings {
  public errors: { message: string; location?: string; input?: string }[] = [];
  public warnings: { message: string; location?: string; input?: string }[] = [];
  public shouldTrack = false;

  reset(): void {
    this.errors = [];
    this.warnings = [];
    this.shouldTrack = false;
  }
}
```

however, in varying tests, the location is assumed to be other types. For example:

Here is is assumed to be a 4 element array:

![location is array](https://user-images.githubusercontent.com/10475866/174309383-b2186c18-e4d7-4c6b-8b0b-bfefcdf7448a.PNG)

Here is is assumed to be an object with 4 elements:

![location is object](https://user-images.githubusercontent.com/10475866/174309409-23fa6ecc-d8a3-4218-965b-d4ec68bc27a8.PNG)

Therefore, I believe that the class should be:

```
export class ErrorsAndWarnings {
  public errors: { message: string; location?: any; input?: string }[] = [];
  public warnings: { message: string; location?: any; input?: string }[] = [];
  public shouldTrack = false;

  reset(): void {
    this.errors = [];
    this.warnings = [];
    this.shouldTrack = false;
  }
}
```

where location type is any.

Would you like me to submit a PR for this?

**Comment by cmoesel** [comment]
Well, this is embarrassing.  That said, I'm surprised that TS isn't complaining and that things still seem to generally work.  If you have a PR ready to go, feel free to submit it and we'll do a little more digging. I'd like to understand how/why we're getting away with this -- and if perhaps we ought to be more consistent about things (in which case, we'd want the `location` type to be more specific rather then `any`).  But a PR with `any` is a good start.
