### ISSUE TITLE
Support manifest property in sushi-config.yaml

### ISSUE THREAD

**Issue by fbove** [FHIR/sushi#1107]
Hi!

Would it be possible to support configuring the [manifest](https://www.hl7.org/fhir/R4/implementationguide-definitions.html#ImplementationGuide.manifest) property inside sushi-config.yaml in order to have it inside the outputted file ImplementationGuide.json

I've seen that's already typed [here](https://github.com/FHIR/sushi/blob/270d65d325f09a97a35de6b42ce8f5fdfd3ea082/src/fhirtypes/ImplementationGuide.ts#L31).

**Comment by cmoesel** [comment]
Hi @fbove.  We didn't implement export of the `manifest` property because the description says:
> Information about an assembled implementation guide, created by the publication tooling.

As such, I think it's intended to be populated by the IG Publisher (or Simplifier or whatever publication tooling you use). What is the use case for wanting to provide that information in the SUSHI config?

**Comment by fbove** [comment]
Hi! I'm using the IG Publisher.
What I'm trying to achieve is having the property manifest.rendering set inside the ImplementationGuide.json file.
When the npm package get's created it says here: [https://confluence.hl7.org/pages/viewpage.action?pageId=35718629#NPMPackageSpecification-PackageManifestpropertiesforIGs](https://confluence.hl7.org/pages/viewpage.action?pageId=35718629#NPMPackageSpecification-PackageManifestpropertiesforIGs) that the url comes from the ImplementationGuide.manifest.rendering.
I guess it's a publisher option but I'm not sure which one yet.

**Comment by cmoesel** [comment]
Hi @fbove.  Thank you for the additional details.  You raise a good question.  I've asked about this on chat.fhir.org here: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Editing.20IG.2Emanifest/near/303918302

**Comment by cmoesel** [comment]
If you take a look at the link above, you'll see that @grahamegrieve confirmed that the `ImplementationGuide.manifest` needs to be handled by the IG Publisher (not the author) -- so it doesn't make sense for SUSHI to allow direct manipulation of it.

Regarding how you can control the `ImplementationGuide.manifest.rendering` value and/or package manifest's `url` value, it sounds like that depends on the situation. You may need to reach out to Grahame directly if you want to chase that down further.
