### ISSUE TITLE
Feature request: Using Slice Definition icon for "Slices for extension" as same as "Slices for elements".

### ISSUE THREAD

**Issue by tmitanitky** [FHIR/sushi#1119]
For slices for elements, the sliced elements are hung under the "Slices for element".
![image](https://user-images.githubusercontent.com/40882114/179397759-4eb0c237-2361-4319-b9a4-48fb2163574c.png)

On the other hand, for slices for extensions, "Slices for extension" and sliced extensions line up on the top level side by side.
![image](https://user-images.githubusercontent.com/40882114/179397889-023a8f89-a87f-40c3-8712-492cb12ff432.png)

As a result, the cardinality for extensions becomes not intuitive. For the above example, it seems you need some kind of extention "in addition to" the `iso-21090-EN-representation` extention, while the min cardinality of 1 for "Slices for extension" just represents the min cardinality of  `iso-21090-EN-representation` extention.

I sugget using Slice Definition Icon also for `Slices for extension` and hanging sliced extensions under the `Slices for extension` just the same as "Slices for elements".

**Comment by cmoesel** [comment]
SUSHI does not generate HTML views of profiles and extensions.  The views in your screenshots come from the HL7 FHIR IG Publisher.  If you'd like to suggest a change in those views, I recommend posting an issue in the [HL7/fhir-ig-publisher](https://github.com/HL7/fhir-ig-publisher) repository.

**Comment by tmitanitky** [comment]
Thanks. Sorry for posting to an inappropriate repository.
