### ISSUE TITLE
e.type error causes SUSHI to skip Instance generation

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#112]
In CancerGenomicsExample.fsh, the very last line is:
`* component[GeneStudied].valueCodeableConcept = HGNC#619728 "STK11" `
When this line is in, SUSHI generates an error:
`error: e.type is not iterable`
and SUSHI does not produce the example instance (mCODEGenomicRegionStudiedExample01).

When this line is commented out, the example instance is produced, and there is no error message.

This was hard to track down, because the line number was missing from the error message.

**Comment by cmoesel** [comment]
This has already been addressed in #107 and will be in the next bug fix release (which we hope to release today).

Sorry that it caused you trouble and was difficult to track down. :-/

**Comment by cmoesel** [comment]
Fixed in 0.6.1
