### ISSUE TITLE
Inconsistent handling of URL assignments

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1122]
SUSHI appears to be inconsistent when assigning values to elements of type `url`.  In some cases it requires the URL be wrapped in `"` `"`, but in others, it does not.  The spec does not directly address this, so we should discuss what the right behavior is. 

Personally, I think that if the URL is the actual value itself (e.g., of a `url` or `uri` element), then you should wrap it in `"` `"`.  If the URL is just a pointer to another entity (like when used in `Reference()`, `Canonical()`, or inline assignments), then it is not wrapped in `"` `"`. _(Edit: I'm not sure about this, actually.)_

The specific behavior that caused this issue is that when you assign the `^url` in a profile or extension, it requires `"` `"`; but when you assign the `^url` in `ValueSet` or `CodeSystem`, it accepts the URL without `"` `"`.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Extension.20id/near/290262701

Full example on FSH Online: https://fshschool.org/FSHOnline/#/share/3Oh1rGs

**Comment by cmoesel** [comment]
I'm not 100% sure my intuition is right. Maybe we should just support both ways across the board (URLs with and without `"` "`).  @markkramerus - do you have an opinion?

If we do make a change that is more restrictive (e.g., requiring `"` `"` where we previously did not require it), then we should run a full regression to understand the implications. If it breaks a bunch of projects, we should consider holding it for 3.0 and/or just warning instead.

**Comment by mint-thompson** [comment]
The new handling for Instance assignment in #1242 resolves this, since unquoted URLs are interpreted as referring to an Instance. URLs that are meant to be assigned literally must be quoted.
