### ISSUE TITLE
Have sushiClient create definitions with snapshot

### ISSUE THREAD

**Issue by nico-ploner** [FHIR/sushi#1128]
Hello sushi-team,

would it be possible for the sushiClient's api to create json resources including their snapshots?
The cli offers the switch --snapshot but the fshToFhir method's options are lacking this property and line 81 of FshToFhir.ts hard codes the snapshot value to 'false'.

Any help is highly appreciated.
Nico

**Comment by cmoesel** [comment]
Hi @nico-ploner.  We can look into this, but it's worth noting that SUSHI's snapshot generation is likely not perfect and differs from the snapshots that the IG Publisher and/or Simplifier would create.  If you plan to publish these resources, it would probably be better to use one of those other tools to generate the snapshots.

**Comment by nico-ploner** [comment]
Hey @cmoesel. Thank you for your response. I'll bear it in mind when creating profiles using SUSHI.
I'd be happy to see SUSHI's client provide this feature some day which allows us to directly use its ouput in code generation tools.

**Comment by cmoesel** [comment]
Ah, yes, I see.  SUSHI's snapshots would probably work fine for code generation.  We'll add this feature to our backlog for consideration in future sprints.

**Comment by joepaquette** [comment]
Ditto @nico-ploner... It would be very good to get rid of the IG Publisher in our workflow just to get `snapshot`  for our code generators!

**Comment by jafeltra** [comment]
This was added in PR #1465. Thanks @joepaquette!
