### ISSUE TITLE
Extensions: Generated URL overpowers manually-created URL

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#1130]
It should be possible to create an extension by profiling Extension, e.g.:

Profile: Laterality
Parent: Extension
Title: "Laterality Extension"
Description: "Extension to specify the side of the body."
* value[x] 1..1
* value[x] only CodeableConcept
* value[x] from http://hl7.org/fhir/ValueSet/bodysite-laterality (required)
* url = "http://foobar/laterality-extension"

Using this method allows the user to bypass the default URL generation based on the IG's canonical URL.  That seems to work OK. However, when the extension is incorporated into a profile, the custom URL gets replaced by the generated URL. 

[See this link ](https://fshschool.org/FSHOnline/#/share/3dp0or3) and look at BodyStructureWithLaterality and you'll see what I mean.

**Comment by cmoesel** [comment]
When including an extension in a profile, you must refer to the extension using its canonical URL.  In your `Laterality` example above, you did _not_ change the canonical URL.  You merely specified a fixed value for `Extension.url`.  But the canonical URL is metadata on the StructureDefinition itself, so you need to use a caret rule:
```
* ^url = "http://foobar/laterality-extension"
```

Here is [your example modified to use ^url](https://fshschool.org/FSHOnline/#/share/3wuXNmr).  It properly includes the extension using the custom canonical URL.
