### ISSUE TITLE
IG Publisher exeuction of SUSHI should not set TestScripts as example resources in generated ImplementationGuide resource

### ISSUE THREAD

**Issue by rettema** [FHIR/sushi#1131]
During the IG Publisher execution of SUSHI, all FSH defined TestScript resources are set as example resources in the generated ImplementationGuide resource. For example,
```
      {
        "reference": {
          "reference": "TestScript/C4BB-Patient-read-validate-json"
        },
        "name": "testscript-C4BB-Patient-read-validate-json",
        "exampleBoolean": true
      },
```

TestScript resources are part of the FHIR Testing Framework and represent executable artifacts and should not be defined as example resources in the generated ImplementationGuide resource. For example,
```
      {
        "reference": {
          "reference": "TestScript/C4BB-Patient-read-validate-json"
        },
        "name": "testscript-C4BB-Patient-read-validate-json",
        "exampleBoolean": false
      },
```

**Comment by cmoesel** [comment]
Hi @rettema.  SUSHI _defaults_ all instances to examples because that is how SUSHI is most commonly used.  You can override this, however, by adding this keyword to each `TestScript` instance:
```
Usage: #definition
```

See: https://hl7.org/fhir/uv/shorthand/reference.html#defining-instances

**Comment by rettema** [comment]
Chris,
That makes sense. I'll use that going forward.
Thanks!
