### ISSUE TITLE
SUSHI should warn when multiple value[x] choices are used

### ISSUE THREAD

**Issue by jafeltra** [FHIR/sushi#1137]
SUSHI should log a warning if multiple value[x] choice elements are applied to an Instance. For example, both `valueString` and `valueCodeableConcept` cannot both be assigned on an Observation instance. In this case, the FHIR validator reports an error, but SUSHI does not.

Example FSH: https://fshschool.org/FSHOnline/#/share/3pKpG5X
Zulip thread: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Multiple.20Observation.20values

**Comment by cmoesel** [comment]
Actually, since this is always _wrong_, I think it should be an error.
