### ISSUE TITLE
Instance property must be an Array, not an Object

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#114]
Elements that are defined as 0..* in resources must be JSON arrays in the instance, even if the cardinality has been constrained, or the array contains just one value. It appears array elements are being rendered as Objects rather than Arrays.

Example -- on master branch, at commit `https://github.com/standardhealth/fsh-mcode/commit/4948b6ebe0018ddf2f9d8d8c53a469de972f059d`

Example: `build\input\resources\Condition-mCODEComorbidConditionExample01.json`

IG Publisher reports:  `Condition.category | error | This property must be an Array, not an Object`

**Comment by cmoesel** [comment]
Hmm... this was something that we intentionally _tried_ to support and I think we even have unit tests that show it working, but there must be some edge case that was missed.  Thanks for reporting.

**Comment by cmoesel** [comment]
Re-opening until it is released.

**Comment by cmoesel** [comment]
Fixed in 0.6.2
