### ISSUE TITLE
SUSHI should allow for concatenations on resolved canonicals

### ISSUE THREAD

**Issue by julianxcarter** [FHIR/sushi#1141]
SUSHI does not currently allow for users to manually add to the url string generated by the `Canonical()` keyword, users would find that capability useful. Support for this could also be extended to the `Reference()` keyword. 

See: 
https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Canonical.20URLs.20containing.20.23/near/296831891
https://fshschool.org/FSHOnline/#/share/3eiX9BX

**Comment by cmoesel** [comment]
This would likely need to be implemented first as an update to the spec (since the spec doesn't support these being used in the middle of strings).  I think this is request is really a language feature request (not just a SUSHI request).

**Comment by jafeltra** [comment]
Since this would require a spec change, I'm going to close this issue here. Changes to the FSH spec should be proposed through the ballot process for the FSH specification.
