### ISSUE TITLE
Revisit Potential Path / Keyword Conflicts in Grammar

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1144]
Now that we support indented rules, there is potential for path / keyword conflicts in the grammar that did not exist before.  For example, the following fails to compile due to the path `exclude`:
```
Instance: MyGroup
InstanceOf: Group
* type = #person
* actual = true
* characteristic
  * code = #clashing
  * valueBoolean = true
  * exclude = false
```
[FSH Online](https://fshschool.org/FSHOnline/#/share/3QiuAlC)

You can avoid this by using the full path, `characteristic.exclude`, but it would be nice if you didn't have to do that.

We should revisit the grammar to see if we can allow for paths that also happen to match keywords.

**Comment by mint-thompson** [comment]
Fixed in #1244
