### ISSUE TITLE
Wish: SUSHI allows decimal values for "Instance"

### ISSUE THREAD

**Issue by stefan-hubert-bl** [FHIR/sushi#1148]
EDIT: ups just recognizing it is duplicate to https://github.com/FHIR/sushi/issues/1132#issue-1337317180.  How can I remove or label as duplicate?

**Example:** https://fshschool.org/FSHOnline/#/share/3L2Pap9
**Expected:** translates into:
`"someField": [
    1.34,
    0,
    -0.1,
    0.1e-13
  ]`
**Observed:** says: `error Cannot find definition for Instance: 0.1e-13. Skipping rule.
  Line: 9`

**Discussion:** isn't `0.1e-13` a valid decimal value as of https://www.hl7.org/fhir/datatypes.html#decimal?
If, however, that limitation applies to Instance items only, it would say it is rather cosmetic issue.

**Comment by cmoesel** [comment]
Thanks, @stefan-hubert-bl.  I've marked it as a duplicate and will close it now.  Please track #1132 for updates.
