### ISSUE TITLE
Codes are not passing validation

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#115]
The IG Publisher is reporting an error validating certain codes.

You can see this error in the QA report when you run the IG Pub.

Example -- on master branch, at commit https://github.com/standardhealth/fsh-mcode/commit/4948b6ebe0018ddf2f9d8d8c53a469de972f059d

Instance:  build\input\resources\Condition-mCODEComorbidConditionExample01.json. Here's how the relevant bit of the resource looks:

```
  "id": "mCODEComorbidConditionExample01",
  "clinicalStatus": {
    "coding": [
      {
        "code": "active"
      }
    ]
  },
```
Here's the resulting error message:

```
Condition/mCODEComorbidConditionExample01: Condition.clinicalStatus | error | None of the codes provided are in the value set http://hl7.org/fhir/ValueSet/condition-clinical\|4.0.1 (http://hl7.org/fhir/ValueSet/condition-clinical, and a code from this value set is required) (codes = null#active) (see Tx log)
```

Here's the relevant part of the Terminology Log:

`<?xml version="1.0" encoding="UTF-8"?><Parameters xmlns="http://hl7.org/fhir"><parameter><name value="codeableConcept"/><valueCodeableConcept><coding><code value="active"/></coding></valueCodeableConcept></parameter><parameter><name value="valueSetMode"/><valueString value="CHECK_MEMERSHIP_ONLY"/></parameter><parameter><name value="valueSet"/><resource><ValueSet><id value="condition-clinical"/><meta><lastUpdated value="2019-10-31T18:29:23.356-04:00"/><profile value="http://hl7.org/fhir/StructureDefinition/shareablevalueset"/></meta><extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-wg"><valueCode value="pc"/></extension><extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status"><valueCode value="trial-use"/></extension><extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"><valueInteger value="3"/></extension><url value="http://hl7.org/fhir/ValueSet/condition-clinical"/><identifier><system value="urn:ietf:rfc:3986"/><value value="urn:oid:2.16.840.1.113883.4.642.3.164"/></identifier><version value="4.0.1"/><name value="ConditionClinicalStatusCodes"/><title value="Condition Clinical Status Codes"/><status value="draft"/><experimental value="false"/><date value="2019-10-31T18:29:23-04:00"/><publisher value="FHIR Project team"/><contact><telecom><system value="url"/><value value="http://hl7.org/fhir"/></telecom></contact><description value="Preferred value set for Condition Clinical Status."/><immutable value="true"/><compose><include><system value="http://terminology.hl7.org/CodeSystem/condition-clinical"/></include></compose></ValueSet></resource></parameter><parameter><name value="profile"/><resource><Parameters><parameter><name value="profile-url"/><valueString value="dc8fd4bc-091a-424a-8a3b-6198ef146891"/></parameter></Parameters></resource></parameter></Parameters>`

**Comment by cmoesel** [comment]
This is happening because FHIR R4 changed `Condition.clinicalStatus` and `Condition.verificationStatus` from `code` to `CodeableConcept` -- so now you need to include the appropriate system when fixing the code.

This is also the case for `AllergyIntolerance`.

**Comment by davidhay25** [comment]
That one stung me as well!

**Comment by cmoesel** [comment]
Yeah, down the line we might build more smarts into SUSHI so it can infer the code system based on the value set binding, but that's not at the top of the list right now.

**Comment by cmoesel** [comment]
@markkramerus -- please close this if you have verified the suggested fix.
