### ISSUE TITLE
Importing and export in another Node app?

### ISSUE THREAD

**Issue by seanmcilvenna** [FHIR/sushi#1162]
Is it possible to import this npm package into another app, and then:

1. Convert a resource to an FSH string (not to the file system)
2. Convert a FSH string into a resource (also not to the file system)

If so, can you point me in the right direction to do these things?

I think I can figure out how to do the second via `exportFhir`... Though, seems like there might be a lot of setup to make that work. 

But, I looked around for a similar class for import to handle my first scenario, and couldn't find anything obvious.

Thanks in advance!

**Comment by cmoesel** [comment]
Hi @seanmcilvenna.  I think you can do what you want via the public APIs we documented for GoFSH and SUSHI.

> Convert a resource to an FSH string (not to the file system)

See the GoFSH API documentation: https://fshschool.org/docs/gofsh/api/

> Convert a FSH string into a resource (also not to the file system)

See the SUSHI API documentation: https://fshschool.org/docs/sushi/api/

That said, these are Node APIs that assume access to a file system and network calls (for downloading dependencies and storing/reading them in the local FHIR cache).  If you need something that will work fully in the frontend of a browser, it gets more complicated...

**Comment by seanmcilvenna** [comment]
Wow! This is _perfect_! You gave me _exactly_ what I need. Thanks _so_ much!
