### ISSUE TITLE
Lengthy List of Constraints on Profile Pages

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#117]
There is a huge list of constraints on each profile page. For example, `ele-1` and `ext-1` are repeated many times -- once for each element. While this might be technically correct,  US Core don't even include a section of constraints. This is a low priority, and probably requires some chat on zulip to see what other IGs are doing.

**Comment by markkramerus** [comment]
https://files.slack.com/files-pri/TKF8N317U-FTCTS6P47/image.png

**Comment by cmoesel** [comment]
direct link to conversation: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Derived.20profile.20snapshot.20missing.20upstream.20invariants/near/186957843

**Comment by cmoesel** [comment]
Julia addressed this in #171, which configures the publisher *not* to show inherited invariants (via an ImplementationGuide JSON parameter).
