### ISSUE TITLE
Unable to target extension with a path

### ISSUE THREAD

**Issue by vadi2** [FHIR/sushi#1187]
I'm unable to target the `cityCode` extension that is part of [ILCore Address datatype](https://simplifier.net/ilcore/ilcoreaddress) & consequently part of the [ILCore Patient profile](https://simplifier.net/ilcore/ilcorepatient). What could be the reason?

FSH code is -

```
Profile: MyPatientIL
Parent: ILCorePatient
Id: MyPatientIL
Description: "An example profile of the Patient resource."
* address.city.extension[cityCode] MS
```

Error is: `No element found at path address.city.extension[cityCode] for FlagRule in MyPatientIL, skipping rule`

FSH online link - https://fshschool.org/FSHOnline/#/share/3uFWcZI, Github project link - https://github.com/vadi2/ProfileAddressExtension.

Included is a profile on a Norwegian patient which has a similar extension, and that works - not in FSH online, but locally once you inflate the right package (`fhir inflate --package hl7.fhir.no.basis`).

**Comment by cmoesel** [comment]
Hi @vadi2. When you access extensions like that, you are accessing them by the slice name that was defined in the profile. Unfortunately for you, ILCore changed the slicename they used for that extension. The version you are referencing in your config (v0.9.1) uses the slice name `citycode`, not `cityCode` (which is the slice name in v0.10.1).  Slice names are case-sensitive, so if you change your FSH to use `citycode` instead, it works.  Here's your example with that modification: https://fshschool.org/FSHOnline/#/share/3FHTtVX

Referencing extensions by their slice name works well when you have control over the profile and slice name -- but in cases like this, where the slice name is coming from another package, you can end up in trouble if they change the slice name. To avoid this type of situation, you can access the extension by its canonical URL instead and SUSHI will find the extension slice that matches and use that.

```
Alias: $CityCodeExt = http://fhir.health.gov.il/StructureDefinition/ext-city-code

Profile: MyPatientIL
Parent: ILCorePatient
Id: MyPatientIL
Description: "An example profile of the Patient resource."
* address.city.extension[$CityCodeExt] MS
```

See: https://fshschool.org/FSHOnline/#/share/3UJb5Vp

**Comment by vadi2** [comment]
Brilliant, thanks!

That's what I get for looking at the latest content instead of a fixed package version.

**Comment by vadi2** [comment]
Is it possible to debug what are the available paths that SUSHI is comparing agaisnt?

**Comment by cmoesel** [comment]
No, but I was thinking a similar thing when I looked at this.  Particularly when it comes to slice or extension paths, it would be nice if SUSHI told you the available slice names when you referenced one that doesn't exist.  If it did that, you probably would have caught this issue right away.
