### ISSUE TITLE
Silent / errors only mode

### ISSUE THREAD

**Issue by vadi2** [FHIR/sushi#1194]
It would be great for SUSHI to have a mode in which it will print warnings/errors only - quiet unless there's a problem. The practical reason for this is that in visual-space constrained environments (think enterprise remote sessions or simply small screens), you always have to scroll up after a SUSHI run to find the actual issues.

There some support from others for this in https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/print.20errors.20only

**Comment by cmoesel** [comment]
This was implemented by #1208.
