### ISSUE TITLE
The filter "concept is-not-a 128462008" was not understood"

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#120]
The IG Publisher complains about ValueSet-PrimaryOrUncertainBehaviorCancerDisorderVS.json:

`Error from server: The filter "concept is-not-a 128462008" was not understood in the context of http://snomed.info/sct`

The FSH looks ok to me:

`* codes from system SCT where concept is-a #363346000 "Malignant neoplastic disease (disorder)" and concept is-not-a #128462008  "Secondary malignant neoplastic disease (disorder)"`

I double-checked the codes are valid, too. I can't figure this one out since similar syntax is accepted elsewhere.

**Comment by cmoesel** [comment]
Looking at the [filter documentation for SNOMED-CT](http://hl7.org/fhir/R4/snomedct.html#filters), it looks like SNOMED-CT only allows the following types of filters:

* `concept is-a [concept id]`
* `concept in [concept id]`
* `constraint = [expression constraint]`
* `expressions = [true/false]`

Note that `is-not-a` is not listed as a valid filter for the SNOMED-CT system (although it may be valid for other systems).  _Maybe_ you could express what you want using `constraint = [expression constraint]`, but I'm not familiar enough with SNOMED-CT expressions to know if that's viable.

**Comment by markkramerus** [comment]
How can that be the case?  In CIMPL, we did this:
```
SCT#363346000  "Malignant neoplastic disease (disorder)"
Includes codes descending from SCT#363346000 "Malignant neoplastic disease (disorder)" and not descending from SCT#128462008  "Secondary malignant neoplastic disease (disorder)"
``` 
and it worked. We also use is-not-a elsewhere in the same FSH file.

**Comment by cmoesel** [comment]
Oh!  I bet that in CIMPL we translated `not descending from SCT#128462008  "Secondary malignant neoplastic disease (disorder)"` into an `excludes`.  You could confirm by looking at the ValueSet JSON.

If that's right, then you can change your FSH to this:
```
* codes from system SCT where concept is-a #363346000 "Malignant neoplastic disease (disorder)"
* exclude codes from system SCT where concept is-a #128462008 "Secondary malignant neoplastic disease (disorder)"
```

**Comment by cmoesel** [comment]
But if `is-not-a` is working in other value sets without the IG Publisher complaining, then I'm not sure what to tell you -- unless the real problem is that the code isn't valid or something.

**Comment by cmoesel** [comment]
@markkramerus -- please close this once you've verified the suggested approach.

**Comment by markkramerus** [comment]
Verified.
