### ISSUE TITLE
Support specifying a version within a contains rule for extensions

### ISSUE THREAD

**Issue by jafeltra** [FHIR/sushi#1204]
Currently, you cannot specify a version of an extension when using a contains rule to add an extension. It would be good to be able to specify the version directly in contains rule using either the extension name, id, or url as you would do in any other contains rule.

This would mean that FSH such as this:

```
* extension contains USCoreEthnicityExtension|5.0.1 named example-ext 1..1
```

should result in a profile with the following differential element:

```json
{
  "id": "Condition.extension:example-ext",
  "path": "Condition.extension",
  "sliceName": "example-ext",
  "min": 1,
  "max": "1",
  "type": [
    {
      "code": "Extension",
      "profile": [
        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity|5.0.1"
      ]
    }
  ]
}
```

FSH Online example that demonstrates current behavior: https://fshschool.org/FSHOnline/#/share/3HrN4hi
Originally reported on Zulip: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/How.20to.20add.20extension.20to.20a.20profile.20with.20canonical.20version

**Comment by mint-thompson** [comment]
Fixed by #1251
