### ISSUE TITLE
SUSHI should support x patch wildcard in package versions

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1219]
The Confluence doc on versions says that the following is allowed as a dependency version: `3.0.x`, meaning the latest patch of `3.0`. SUSHI should support this.

See: https://confluence.hl7.org/pages/viewpage.action?pageId=35718629#NPMPackageSpecification-Versionreferences

**Comment by vassilpeytchev** [comment]
Also, for sushi-config.yaml the `dependencies` that are the source for `ImplementationGuide.dependsOn` need to have an option for latest published version, since `ImplementationGuide.dependsOn` allows the specification of only a canonical without any version information.
