### ISSUE TITLE
Consider reporting a warning when no menu.xml is present

### ISSUE THREAD

**Issue by jafeltra** [FHIR/sushi#1224]
When there is no `menu.xml` in an IG, the IG Publisher will stop. SUSHI should consider including a warning when a `menu` is not provided in `sushi-config.yaml` or as separate file to help users realize the issue sooner in the process.

Some things to consider - we probably do not need this warning if `FSHOnly` is `true` in the sushi-config.

**Comment by cmoesel** [comment]
Whoops. Looks like this is a duplicate of #1161.
