### ISSUE TITLE
Create directory that will auto-compile Binary resources for Logical Model instances

### ISSUE THREAD

**Issue by awatson1978** [FHIR/sushi#1232]
Regarding the long-standing work-around for instances of Logical Models needing to be compiled to Binary:
https://fshschool.org/docs/sushi/tips/#instances-of-logical-models

Feature request:  Have a directory that will auto-compile Binary resources for Logical Model instances therein.  This should be a compile step built in the tools, so the user doesn't have to write their own Binary encoder and tooling pipeline.

**Comment by grahamegrieve** [comment]
Sushi doesn't have to do conversion to binary - in fact, if there's a logical model definition, it's better not to, it's better to leave it native and use the http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-logical extension

Example in https://github.com/FHIR/fhir-tools-ig:

* instance: https://github.com/FHIR/fhir-tools-ig/blob/master/input/cdshooks/Binary-CDSHookServices.json
* logical model: https://github.com/FHIR/fhir-tools-ig/blob/master/input/resources/structuredefinition-CDSHooksServices.json
* IG registration: https://github.com/FHIR/fhir-tools-ig/blob/master/input/tools-ig.xml#L93
* output: https://build.fhir.org/ig/FHIR/fhir-tools-ig/Binary-CDSHookServices.html

if there's no structure definition, then it needs to be a binary.

**Comment by cmoesel** [comment]
As @grahamegrieve noted above, the IG Publisher tooling can take care of the base64 encoding for you, as long as you follow the correct formula. The documentation in FSH School that @awatson1978 pointed to should be sufficient to support the auto-encoding.

@grahamegrieve - why is the `implementationguide-resource-logical` extension needed? Can't you just point `exampleCanonical` (R4) or `profile` (R5) to the logical it is an example of?

**Comment by cmoesel** [comment]
@awatson1978 - does this meet your need or are you looking for something different?

**Comment by awatson1978** [comment]
No, I haven't been able to replicate it.  After a week of trying, this is all I'm getting:

<img width="1396" alt="Screenshot 2023-03-11 at 11 57 15 PM" src="https://user-images.githubusercontent.com/675910/224527144-952cd944-81db-4f6c-9e8a-24a5ae8bac68.png">

**Comment by awatson1978** [comment]
https://github.com/FHIR/sushi/issues/1238

**Comment by cmoesel** [comment]
Closing this as I think the solution is the same as #1238, but please feel free to re-open it if needed.
