### ISSUE TITLE
Improve error when using a value set in a primitive code assignment

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1239]
One common mistake is for users to use a value set instead of a code system when specifying a code (e.g., `MyVS#mycode`). When this happens, SUSHI issues an error saying "A CodeSystem must be used." When the target type is a primitive `code`, however, it's actually most appropriate to specify _only_ the code.

If we can detect that situation, we should change the error from:

> Cannot assign http://hl7.org/fhir/ValueSet/observation-status at path Observation.status. A CodeSystem must be used.

to

> Cannot assign http://hl7.org/fhir/ValueSet/observation-status at path Observation.status. When assigning to a primitive code, you need only specify the code (e.g., #mycode). If you wish to specify the system anyway, you must specify the CodeSystem (not the ValueSet).

**Comment by jafeltra** [comment]
The error message has been updated to be more clear in #1275.
