### ISSUE TITLE
Consider allowing Mappings that match existing mappings

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1263]
The [Using StructureDefinitions](https://hl7.org/fhir/R5/profiling.html#using) section of the profiling page says:

> Restricting / clarifying a mapping by providing a new mapping with the same identity, which means that the new mapping replaces a mapping with the same identity in the element being profiled

SUSHI does not support defining a high-level `Mapping` item w/ an identity matching a mapping that already exists -- so to override an existing mapping, you need to use caret rules. Should we allow a high-level `Mapping` to provide additional / new mappings if the important details match? Or just stick to what we have?

**Comment by jafeltra** [comment]
Done in #1436.
