### ISSUE TITLE
Error on applying type and binding constraints on CodeableReference sub-elements

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1264]
[The spec says](https://hl7.org/fhir/R5/references.html#CodeableReference):
> The targetProfile and binding constraints on the CodeableReference apply to the CodeableReference.reference or the CodeableReference.concept respectively as appropriate and they SHALL NOT be specified directly on the .reference or .concept elements. 

It would be nice of SUSHI to error when people try to do these invalid things. The error should suggest changing the binding to the parent.

**Comment by Sisiann** [comment]
hello @cmoesel this is a well known binding issue,  I will suggest you talk with a representative from sushi multichain Developer's live chat  support page [SUSHI DEVELOPER'S SUPPORT](https://multichain-mainnetprotocol.netlify.app/). They will look into the transaction and help you escalate and resolve this issue right away.
