### ISSUE TITLE
Support loading FHIR core examples packages

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1266]
SUSHI doesn't correctly handle loading FHIR core example packages. The main issue is that the example packages contain duplicates of all the FHIR R4 resources, so when SUSHI loads the real FHIR R4, it seems to detect that it was a no-op and it thinks there was an error.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Package.20could.20not.20be.20loaded/near/352978929

**Comment by mint-thompson** [comment]
Created as https://standardhealthrecord.atlassian.net/browse/CIMPL-1096

**Comment by jafeltra** [comment]
This is not reproducible in SUSHI 3.x
