### ISSUE TITLE
Bad links in Detailed Description page

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#128]
There are a large number of QA errors reported by the IG Publisher about 404 links on the Profile "Detailed Description" pages. The links that are on the page are misconstructed, for example, `http://hl7.org/fhir/R4/StructureDefinition-CancerStageParent.html/observation.html#notes`. The SD that the page was constructed from only has the last part, as follows:
```
"comment": "For a discussion on the ways Observations can be assembled in groups together see [Notes](observation.html#notes) below."
```
Somewhere in the Publication process, the wrong root URL got added. The correct URL would have been `http://hl7.org/fhir/R4/observation.html#notes`.  

Is this in the IG Publisher? Something in SUSHI??

**Comment by markkramerus** [comment]
Lloyd's responses on chat: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Bad.20links.20on.20Detailed.20Description.20tab

**Comment by cmoesel** [comment]
When we create profiles, we start by cloning the base resource and then constraining it. Maybe we should be removing the "comment" field since it's really a comment about the base resource (and not necessarily the profile)? Perhaps the same goes for "description" and other fields? Clearing "comment" when we create a profile would fix at least this one specific instance noted above.

**Comment by cmoesel** [comment]
I've proposed what fields should be cleared vs kept.  See: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Bad.20links.20on.20Detailed.20Description.20tab/near/186460459

**Comment by markkramerus** [comment]
I don't see `comment` in that list, and that's where most of the bad links are. But in general, we should clear those fields.

**Comment by cmoesel** [comment]
Well, shoot, you're right.  The `comment` field is in `ElementDefinition` -- which means that for every one we clear, I think we'd need a corresponding differential.  Which we don't want.  So this doesn't completely solve the problem...

**Comment by cmoesel** [comment]
I'll leave this issue as-is to represent the problem with "comment".

I've created #157 to represent the general clearing of top-level metadata.

**Comment by cmoesel** [comment]
Closing as SUSHI 0.9.0 now generates only the differential by default, which resolves the broken URL errors in the snapshot elements.
