### ISSUE TITLE
Unable to set the .text element

### ISSUE THREAD

**Issue by davidhay25** [FHIR/sushi#129]
These lines:

* ^text.status = #additional
* ^text.div = "<div xmlns=\"http://www.w3.org/1999/xhtml\">text</div>"

result in this error:

error: Cannot fix string value: <div xmlns="http://www.w3.org/1999/xhtml">text</div>. Value does not match element type: xhtml
  File: /Users/davidhay/IG/registry/shorthand/profile-HpiPractitioner.fsh
  Line: 8

**Comment by cmoesel** [comment]
Thanks for reporting this.  We already were tracking this in our internal backlog but hadn't made a public bug for it.  Team, this is the same as _CIMPL-202: FSH: Support for fixing an xhtml element to a string._  Let's bump up priority on this one.

**Comment by cmoesel** [comment]
Fixed in 0.6.2
