### ISSUE TITLE
ImplementationGuide.definition.resource.name not populated correctly for SUSHI generated ActorDefinition, Requirements, TestPlan and TestScript resource types

### ISSUE THREAD

**Issue by rettema** [FHIR/sushi#1296]
The FHIR IG Publisher and HL7 IG Template have been updated to include a new "Testing" tab page on all canonical resource types when TestPlan and/or TestScript resources are linked or reference those canonical resources. When reviewing the rendered "Testing" tab page, the listings of TestPlan and TestScript resource links are displaying the TestPlan.name and TestScript.name values instead of the expected TestPlan.title and TestScript.title values. However, this is only happening when the TestPlan and TestScript resource instances are generated by SUSHI from FSH definitions.

I have reviewed the SUSHI source code and found where this occurs - the **IGExporter.ts** **_addResourcePackage(referenceKey, pkgResource, configResource)_** method that processes these SUSHI generated resources is casting the ActorDefinition, Requirements, TestPlan and TestScript resource types as an **InstanceDefinition** class where the title attribute is not expected to exist. Since the ActorDefinition, Requirements, TestPlan and TestScript resource types implement the CanonicalResource interface, they do have the title attribute defined which needs to be used to populate the corresponding **ImplementationGuide.definition.resource.name** value.

_FYI - The **ImplementationGuide.definition.resource.name** value is used for the link name(s) in the IG pages._

The current logic is:

```
  private addPackageResource(
    referenceKey: string,
    pkgResource: StructureDefinition | ValueSet | CodeSystem | InstanceDefinition,
    configResource?: ConfigurationResource
  ): void {
    const newResource: ImplementationGuideDefinitionResource = {
      reference: { reference: referenceKey }
    };
    if (pkgResource instanceof InstanceDefinition) {
      newResource.name =
        configResource?.name ?? pkgResource._instanceMeta.title ?? pkgResource._instanceMeta.name;
      ...
```

A simple update to this logic to test for the existence of the title attribute will correct this issue as follows:

```
  private addPackageResource(
    referenceKey: string,
    pkgResource: StructureDefinition | ValueSet | CodeSystem | InstanceDefinition,
    configResource?: ConfigurationResource
  ): void {
    const newResource: ImplementationGuideDefinitionResource = {
      reference: { reference: referenceKey }
    };
    if (pkgResource instanceof InstanceDefinition) {
      const title = typeof pkgResource.title === 'string' ? pkgResource.title : null;
      if (title) {
        newResource.name = title;
      } else {
        newResource.name =
          configResource?.name ?? pkgResource._instanceMeta.title ?? pkgResource._instanceMeta.name;
      }
```

**Comment by cmoesel** [comment]
Hi @rettema -- I have not had time to investigate this, but glancing over it now, I believe this _should_ work if you use the `Title:` keyword on your instance.  Are you using `Title: "Some Title"` when you declare your instances? Or are you setting it only via a rule (`* title = "Some Title"`)? In SUSHI 3.0, you *should* need to only use `Title:` and it will auto-set the title in the instance (and IG JSON) for you.

**Comment by rettema** [comment]
@cmoesel -- I just confirmed that defining `Title: "Some Title"` for the FSH TestScript instance generates the expected **ImplementationGuide.definition.resource.name** values. Thank you.

However, I do still consider this to be an issue as FSH authors are not required to use the `Title: "Some Title"` within the instance declaration. I believe that SUSHI should still recognize the `title` attribute value regardless of how it's generated. As I stated above, my code modification to the **IGExporter.ts _addResourcePackage(referenceKey, pkgResource, configResource)_** method does handle this case where the `title` attribute is only set via the rule (`* title = "Some Title"`).

**Comment by cmoesel** [comment]
Understood -- and that is something we'll consider. We need to decide the order of precedence. If someone sets the title via `Title:` and the `title` element via a rule -- and they are different -- which one goes into the guide? I think `Title:` should win in that case, but we'll need to discuss.

I offered the `Title:` approach here so that you have a way forward as we consider how to best integrate a title set by rules.

**Comment by rettema** [comment]
I agree - `Title:` then `* title` would be my vote 👍 

Thanks!
