### ISSUE TITLE
SUSHI should allow binding to Logical Models that have the #can-bind characteristic

### ISSUE THREAD

**Issue by jafeltra** [FHIR/sushi#1347]
Logical Models support specifing type characteristics through the `Characteristics` keyword. One of the values supported by this extension is `can-bind`, which states that the type can be bound to a terminology. SUSHI should allow Logical Models that have this characteristic specified to be used in bindings. If the characteristic is not specified, but the type is used in a binding, a warning should be logged (this should be similar to the behavior in SUSHI when a Logical Model is used as a reference without the `can-be-target` characteristic).

**Comment by cmoesel** [comment]
@benjaminflessner -- Thanks for the heads up. @jafeltra will be working on this in our current development sprint, so you should see a solution soon (some time in the next two weeks or so).
