### ISSUE TITLE
Required status field defaults to `active`

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#138]
`StructureDefinition`, `ValueSet`, and `CodeSystem` has `status` fields that are `1..1`.  Since they're `1..1`, we default to a value (`active`).  But... we probably should not be doing this, because we really don't know.  We probably should create a `Status:` keyword and force the author to declare it.  But... at this point that would cause currently valid FSH definitions to start failing, so... we should discuss:

* should we add a `Status:` keyword?
* should it be required?
* if not required, what should we default to?

**Comment by ngfreiter** [comment]
@cmoesel do we want to keep this open? Is this something that would make sense to put on the FSH ballot and address there? If we plan to do that I'm fine with keeping this open. If we don't want to comment, then is it time to close this one?

**Comment by cmoesel** [comment]
Let's see if we get any ballot comments on it and go from there...

**Comment by cmoesel** [comment]
At this point we haven't got any strong feedback against the current approach, so... time to close this issue.
