### ISSUE TITLE
sushi-config.yaml property "name:" omission causes warning, no error

### ISSUE THREAD

**Issue by rpassas** [FHIR/sushi#1383]
Leaving an empty `name:` for a property in sushi-config.yaml generates a warning (that I missed), but causes the publisher to fail. It took me a minute to realize because the publisher error is simply "jsonNull." Having sushi throw an error, rather than a warning, would align the issue with the publisher generating an error and potentially save time troubleshooting.

**Comment by cmoesel** [comment]
Hi @rpassas. Are you referring to the top-level `name` (name of the IG), the `name` specified in the list of resources, or a different `name`?

**Comment by jafeltra** [comment]
We cannot reproduce this. It is possible the behavior has changed since this issue was reported. Please reopen the issue if this is still a problem.
