### ISSUE TITLE
Sushi build adds copyrightYear and releaseLabel to definition.parameter which is unsupported by R4 implementation guide

### ISSUE THREAD

**Issue by vikas-kph** [FHIR/sushi#1392]
Susi build adds copyrightYear and releaseLabel to a field with a required Binding that does not support those codes
https://fhir-ru.github.io/implementationguide-definitions.html#ImplementationGuide.definition.parameter 

GuideParameterCode: https://fhir-ru.github.io/valueset-guide-parameter-code.html

As per Sushi, documentation, this is intended behavior
https://fshschool.org/docs/sushi/configuration/#fsh-and-ig-processing-full-configuration

**Comment by cmoesel** [comment]
Yes, these parameters were made necessary by the publisher and template system subsequent to R4 being published. It wasn't possible to update the value set at that time, so the publisher allows for this particular violation. In fact, it converts these unlisted parameters into extensions as part of its processing and outputs a new IG JSON file.

We have considered having SUSHI add them as extensions in the first place -- but given that the IG Publisher accepts them as-is, there isn't high value in making this change. Still, we will consider it again!
