### ISSUE TITLE
Pulling IG Publisher Scripts from wrong address

### ISSUE THREAD

**Issue by sebg-mio42** [FHIR/sushi#1393]
sushi/src/utils/Processing.ts currently pulls from http://raw.githubusercontent.com/HL7/ig-publisher-scripts/main/*
This causes an issue behind a proxy because the proxy is only used for https requests.

In my opinion the simplest solution would be to have SUSHI pull from https://raw.githubusercontent.com/HL7/ig-publisher-scripts/main/* instead. 

Is there any reason that this should be http?

**Comment by cmoesel** [comment]
I don't recall a reason for that. We'll take a look and switch over to https (assuming we don't find any reason to stay on http).
