### ISSUE TITLE
SUSHI: Cannot find definition for Instance at CodeSystem.url

### ISSUE THREAD

**Issue by realizm** [FHIR/sushi#1396]
```
CodeSystem: HiraMedicalSubject
Id:         hira-medical-subject
Title:     "Hira Medical Subject"
Description: "Medical Subject Codes"

//This is the intended URL for CodeSystem. (not yet exist)
* ^url =  https://example.org/CodeSystem/hira-medical-subject 

* #00 "일반의"
```
It worked normally in SUSHI 2.x, but an error occurred in SUSHI 3.x.

**Error log**
error Cannot find definition for Instance: https://hira.or.kr/CodeSystem/hira-medical-subject. Skipping rule.
  File: C:\IdeaProjects\platform\portal\ImplementationGuide\input\fsh\CodeSystem\hira-medical-subject.fsh

**Comment by cmoesel** [comment]
Hi @realizm. Technically, when assigning to an element that has `url` or `uri` datatype, you need to assign it as a string. SUSHI 2.x was more lenient about this, but that caused some unexpected issues in other places, so we tightened it up in SUSHI 3.0. It will work if you do this instead:
```
* ^url =  "https://example.org/CodeSystem/hira-medical-subject"
```
