### ISSUE TITLE
Support Special Rules for Contained CodeSystems in ValueSets

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1435]
Based on [this Zulip conversation](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Contained.20code.20system.20in.20the.20value.20set/near/424938537), it is invalid for `ValueSet.compose.include.system` (as well as its `exclude` variant) to set the uri value to a fragment (e.g., `#foo`). This means that the standard way of referencing a contained CodeSystem will not work.

Instead:
1. Use the contained CodeSystem's full canonical URL as the value of `ValueSet.compose.include.system`
2. Put a [valueset-system](https://hl7.org/fhir/extensions/StructureDefinition-valueset-system.html) extension on `ValueSet.compose.include.system` and set its `valueCanonical` to the fragment pointing to the id of the contained CodeSystem (e.g., `#foo`)

Authors can do this the hard way right now (setting the values directly), but I suspect if they use `Canonical(ContainedCodeSystem)`, it might do the wrong thing and directly insert a fragment. We should try to detect this situation and do the right thing:
* At the least _don't_ convert the `ValueSet.compose.{include|exclude}.system` value to a fragment, even when there is a matching contained CodeSystem.
* _Maybe_ go the next step and insert the extension if it has not been manually added already.

Also see: https://jira.hl7.org/browse/FHIR-44896

**Comment by mint-thompson** [comment]
Add to backlog as https://standardhealthrecord.atlassian.net/browse/CIMPL-1246

**Comment by mint-thompson** [comment]
This has been resolved by #1520 .
