### ISSUE TITLE
Allow setting version and releaseLabel from command line

### ISSUE THREAD

**Issue by LodewijkSioen** [FHIR/sushi#1439]
This is a feature request for those of us who use a pipeline to publish our IG. In our company we use Git tags to trigger the publishing process. Right now we have a step in our pipeline that will update the sushi-config.yaml file to set the `version` and `releaseLabel` properties based in the tag name. Right now this is done with some dirty powershell scripting.

It would be nice if we could just override these parameters from the command line like this:

`sushi . --igVersion "1.3.5-alfa.1" --releaseLabel "qa-preview" `

**Comment by cmoesel** [comment]
This is an interesting idea. Would you propose that this should actually change the `sushi-config.yaml` file on disk as well, or would you expect the file on disk to stay as-is even if you override its values on the command line?

**Comment by LodewijkSioen** [comment]
I would not change the config file on disk as that would mean changing a file that is under version control. This could lead to problems when checking out the latest version on the next build.

**Comment by LodewijkSioen** [comment]
So I thought to give it a try and this came out: #1442

**Comment by jafeltra** [comment]
Completed in #1442
