### ISSUE TITLE
Multi line elements

### ISSUE THREAD

**Issue by davidhay25** [FHIR/sushi#147]
I created a multi line text entry (to simulate long text). Worked fine, but got '\n' in the output so not valid xhtml...

```
* text.div = "<div xmlns='http://www.w3.org/1999/xhtml'>
Dr Multi
<ul>
<li> item 1 </li>
<li> item 2 </li>
</ul>

</div>"
```

``` "text": {
    "div": "<div xmlns='http://www.w3.org/1999/xhtml'>\nDr Multi\n<ul>\n<li> item 1 </li>\n<li> item 2 </li>\n</ul>\n\n</div>",
    "status": "additional"
  },
```

**Comment by cmoesel** [comment]
Ah, good find.  We should probably be stripping newlines for XHTML.  And maybe stripping whitespace between tags as well...  Sounds annoying.  Maybe we can find a library for it. ;-)

**Comment by davidhay25** [comment]
https://www.npmjs.com/package/sanitize-html  ?

**Comment by cmoesel** [comment]
Thanks for the suggestion.  I looked at it, but that seems a bit too destructive to me.  It requires a whitelist of allowed tags, strips out disallowed tags, strips out comments, etc.  But you motivated me to do some additional searching.  I think this is actually what we want:
https://www.npmjs.com/package/html-minifier
