### ISSUE TITLE
Add support for CanonicalResource as a parent of a Resource

### ISSUE THREAD

**Issue by mint-thompson** [FHIR/sushi#1477]
Transferred from internal JIRA issue originally created 2022-05-17.

FHIR R5 adds the [CanonicalResource](http://hl7.org/fhir/5.0.0-snapshot1/canonicalresource.html) definition, which is an interface. Interfaces provide element definitions, but these definitions are not automatically inherited. There is some ongoing discussion regarding the use of interfaces: see the following links for details

* https://jira.hl7.org/browse/FHIR-27839 
* https://chat.fhir.org/#narrow/stream/179280-fhir.2Finfrastructure-wg/topic/Interfaces.20and.20ancestors.20and.20patterns/near/273561459 
* http://hl7.org/fhir/5.0.0-snapshot1/uml.html#interfaces

Although the approach to interfaces may change, we should probably support them the way they’re defined now. I think this mainly affects the Resource: capability in FSH.  When creating a resource, if the author adds an element that matches an element from CanonicalResource, SUSHI should allow that (since FHIR says you should redeclare elements from interfaces) - but it also should ensure that you don’t violate any constraints on that element in the interface (e.g., try to make a 0..1 into a 0..*).  If an author does not explicitly add an element from an interface, then it shouldn’t be in the resource’s snapshot.  This likely also has implications for GoFSH.

There’s probably more investigation and understanding needed here.  I expect we’ll learn as we go.

**Comment by cmoesel** [comment]
FHIR R5 changed directions before the official R5 was released -- and `CanonicalResource` is no longer in the official hierarchy chain. This issue is no longer relevant.
