### ISSUE TITLE
Apply ElementDefinition tree strategy to more functions

### ISSUE THREAD

**Issue by mint-thompson** [FHIR/sushi#1486]
Transferred from internal JIRA issue originally created 2024-03-21.

Tree relationships were added to ElementDefinition as part of an initial set of optimizations for Instance export (https://github.com/FHIR/sushi/pull/1443). These optimizations apply to the parent and children functions. However, there are other places where optimization may be possible by avoiding having to operate on the full list of elements for a StructureDefinition. Find those places and optimize their implementations.

**Comment by jafeltra** [comment]
Completed with #1500
