### ISSUE TITLE
QA messages error

### ISSUE THREAD

**Issue by alejosv** [FHIR/sushi#1491]
After running `./_genonce.sh` and checking `qa.html` in the browser with a freshly initialized project, the errors section shows two errors:

|Path |Severity |Message|
|:-------|-------------|:-------------|
|StructureDefinition.text.div | error | Hyperlink 'StructureDefinition-MyPatient-definitions.html#rPatient' at 'div/table/tr/td/a' for 'Patient' does not resolve|
|StructureDefinition.text.div | error | Hyperlink 'StructureDefinition-MyPatient-definitions.html#rPatient.name' at 'div/table/tr/td/a' for 'name' does not resolve|

Previous versions of `_genonce.sh` notified these messages as warnings, even though they are not issues with the FSH files.

This is my environment:
```
$ node -v 
v18.17.1

$ npm -v 
10.8.1

$ java -version: 
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)

$ jekyll -v
jekyll 4.3.3

$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

$ sushi -v
SUSHI v3.11.0 (implements FHIR Shorthand specification v3.0.0-ballot)

FHIR IG Publisher Version 1.6.14 (Git# 8074c42c0755). Built 2024-07-04T03:47:02.626Z

```
Isn't it supposed to generate any errors?

**Comment by cmoesel** [comment]
Hello @alejosv. The `_genonce.sh` script runs the IG Publisher, and the IG Publisher creates the `qa.html` file. As such, this is not really a SUSHI bug. SUSHI appears to be creating its output correctly -- but the IG Publisher is creating (or reporting) invalid links related to the profiles.

Looking at chat.fhir.org, it seems that this is a known issue and the IG Publisher team is working on it. See: https://chat.fhir.org/#narrow/stream/179239-tooling/topic/latest.20IG.20Publisher.20console.20messages/near/449122631

**Comment by cmoesel** [comment]
Actually, it looks like it was fixed in the latest IG Publisher released today. See: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Hyperlink.20.2E.2E.2E.20does.20not.20resolve/near/449338485

Please run `_updatePublisher.sh` to update your publisher and then try again.

**Comment by alejosv** [comment]
Thanks @cmoesel fffectively was a IG publisher issue, I reported too in the IG publisher repository ... 👍🏼
