### ISSUE TITLE
SUSHI MappingExporter does not consider Mapping rules when merging mappings

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1501]
When authors define a `Mapping`, SUSHI attempts to merge the mapping into the set of existing mappings based on the `Mapping`'s declared `Id:` (and FHIR mapping's `identity`), additionally checking its `Title:` and `Target:` values for conflicts (with FHIR mapping's `name` and `uri` respectfully). I.e.

```ts
const matchingParentMapping = parent?.mapping?.find(
  (m: StructureDefinitionMapping) => m.identity === fshDefinition.id
);
if (matchingParentMapping != null) {
  const isMatchingTitle = fshDefinition.title
    ? fshDefinition.title === matchingParentMapping.name
    : true;
  const isMatchingTarget = fshDefinition.target
    ? fshDefinition.target === matchingParentMapping.uri
    : true;
  // ... more code using isMatchingTitle and isMatchingTarget values...
}
```

Now that FSH 3.0 supports rules, the `identity`, `name`, and `uri`, could be set via rules (not just keywords), so we _should_ be checking those as well. And just to make it even more fun, don't forget that rules _could_ be added using RuleSets!

**Comment by jafeltra** [comment]
FSH 3.0 actually doesn't support AssignmentRules on Mappings, so this issue isn't applicable.
