### ISSUE TITLE
Invalid extension context syntax seems to compile

### ISSUE THREAD

**Issue by Fronq** [FHIR/sushi#1525]
Hi I noticed that extension contexts formatted as `* ^context.type = #element` are being successfully compiled when from my knowledge the correct FSH syntax should be something along the lines of `* ^context[+].type = #element`.

**Comment by cmoesel** [comment]
This is allowed because [the spec says](https://hl7.org/fhir/uv/shorthand/reference.html#array-paths-using-numerical-indices):
> If the index is omitted, the first element of the array (`[0]`) SHALL be assumed.

So `^context.type` is equivalent to `^context[0].type`.
