### ISSUE TITLE
Block comments on a single line cause syntax errors

### ISSUE THREAD

**Issue by kjmahalingam** [FHIR/sushi#155]
Block comments are typically meant to be used as multi-line comments, such as this:
```
/*
Comment
Comment
/*
```
Using a block comment on a single line like below causes a syntax error:
```
/* Comment Comment */
```
Although it is unlikely that this will be an issue, since we have support natively for single-line comment syntax with `//`, this is an unintended error and should be resolved.

**Comment by cmoesel** [comment]
Fixed by #316.
