### ISSUE TITLE
Sushi does not allow a StructureDefinition name or id = FHIR resource type

### ISSUE THREAD

**Issue by znatty22** [FHIR/sushi#175]
These  fail:
```
# Patient.fsh

Profile:        Patient
Parent:         Patient
Id:             kidsfirst-patient
Title:          "Kids First Patient"
Description:    "Kids First Patient Structure Definition."
```

```
# Patient.fsh

Profile:        KidsFirstPatient
Parent:         Patient
Id:             patient
Title:          "Kids First Patient"
Description:    "Kids First Patient Structure Definition."
```

![image](https://user-images.githubusercontent.com/10283712/73601312-730e4900-45b3-11ea-987b-c28a34751c57.png)

This works:
```
# Patient.fsh

Profile:        KidsFirstPatient
Parent:         Patient
Id:             kidsfirst-patient
Title:          "Kids First Patient"
Description:    "Kids First Patient Structure Definition."
```
![image](https://user-images.githubusercontent.com/10283712/73601317-9e913380-45b3-11ea-9ffc-2c2be5021bb6.png)

The error seems to be due to the StructureDefinition's `name` or `id` being one of the FHIR resource types (`Patient`). However, the FHIR spec for `StructureDefinition` does not indicate this is a violation of the spec.

**Comment by cmoesel** [comment]
Ah...  Good catch.  We have some things to work through regarding naming and name resolution/scope.  This is clearly an instance of where we're clashing some names.  Thanks for the reproducible issue.

**Comment by ngfreiter** [comment]
To update this issue, the first case:
```
# Patient.fsh

Profile:        Patient
Parent:         Patient
Id:             kidsfirst-patient
Title:          "Kids First Patient"
Description:    "Kids First Patient Structure Definition."
```
has been fixed, now when you do this, you get a nice error message along the lines of:
```
```
