### ISSUE TITLE
FSH should allow explicit declaration of all important StructureDefinition fields

### ISSUE THREAD

**Issue by znatty22** [FHIR/sushi#176]
FSH should allow a user to explicitly define the following additional `StructureDefinition` fields: 
`name`, and the canonical `url` suffix. If these are provided by the author, use these. Otherwise, auto-populate them using the `id` if it is defined.

For example right now:
```
Profile: MyProfile  --> StructureDefinition.name = MyProfile
Id: my-patient      -->  StructureDefinition.url = <canonical base>/my-patient
```

Desired state:
```
Profile: Patient       --> StructureDefinition.url = <canonical base>/Patient
Id: kids-first-patient --> StructureDefinition.id = kids-first-patient
Name: KidsFirstPatient --> StructureDefinition.name = KidsFirstPatient
Title: "Kids First Patient" --> StructureDefinition.title = Kids First Patient
```

This is important because `name`, `id`, and canonical `url` suffix can all be different, especially the latter two. For example, there may be cases where one wants to let the server auto-generate the `id` and use the canonical URL as the permanent globally unique identifier.

**Comment by cmoesel** [comment]
I'll need to look, but I seem to remember the IG Publisher issuing errors if the `url` did not take the form `<canonical base>/<type>/<id>`.  We can revisit to see if this is actually a requirement or not.  It's been a while since I tried something different regarding how the URL is made up.

**Comment by ngfreiter** [comment]
We do now have separate keywords for `Id` and `Title`. We do not give a method for making the canonical `url` different. I found from a quick test that if the canonical `url` does not end with `/<id>`, the following error is given from the IG Publisher:
![image](https://user-images.githubusercontent.com/52747882/80992592-bde46a80-8e07-11ea-9fb1-49ba78820257.png)

For that reason, I think it is fair to stick with our current approach, with the flexibility of now being able to specify `Title` and `Id`. So I am going to close this issue.
