### ISSUE TITLE
System URI containing # syntax question

### ISSUE THREAD

**Issue by ahenket** [FHIR/sushi#180]
In The Netherlands we have [a few systems](http://hl7.nl/wiki/index.php?title=OIDs_en_FHIR_System_URIs) where the FHIR system uri contains a #. This would, unless escaped, lead to an issue in the shorthand syntax.

The documentation does not appear to document how to properly escape that.

**Comment by cmoesel** [comment]
Uh, yeah.  That's probably a problem w/ the current implementation of SUSHI.  Is this seldom enough that escaping `#` is reasonable?  Or does it happen often enough that we should reconsider the `#` syntax for separating system and code?
