### ISSUE TITLE
Scope of extension names is global (should it be?)

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#182]
We have noticed that extensions can clash or be confused with extensions of the same name occurring elsewhere. This could be a problem, especially when importing externally-defined extensions that the FSHerfolk don't control. I'm not sure if the url could differentiate if the names are the same. But this leads to some unexpected behavior, especially when folks are assuming the in-line extension is locally scoped.

**Comment by cmoesel** [comment]
Yes, David Hay has also noted this issue (#86).  It seems like maybe the best approach is to consider requiring that all external entities be referenced by their canonical URL (or an alias that points to their canonical URL).

**Comment by cmoesel** [comment]
Fixed by #264.
