### ISSUE TITLE
Change extension card to 0..0 in simple extensions; value[x] to 0..0 in complex extensions

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#183]
It seems FSHers have found it necessary to explicitly zero out the unused elements in extension (depending on whether it is complex or simple). Seems not to complete the publishing process unless they do this. But SUSHI should know which is which and zero out the appropriate element.

**Comment by cmoesel** [comment]
Agreed, we can (and should) zero out the unused element (`extension` or `value[x]`).
