### ISSUE TITLE
Bug: error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lawley** [FHIR/sushi#184]
The following FSH file generates the error:
error: Cannot read property 'length' of undefined

But the same input with the extension on `compose.include.extension` instead works just fine.

```fsh
Profile: BoostedValueSet
Parent: ValueSet
Id: boostedvalueset
Title: "Boosted ValueSet"
Description: "Any ValueSet that uses the ValueSetBoost extension"
* compose.exclude.extension contains ValueSetBoost 0..* 

Extension: ValueSetBoost
Id: boost
Title: "ValueSet boosting"
Description: "boosting extension"
* value[x] only decimal
```

**Comment by cmoesel** [comment]
Thanks for the report.  We just discovered last week that we're not properly handling contentreferences.  E.g., what gets visualized as a link in the doc:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/2278253/73658250-03a36280-4662-11ea-9e56-34583a3faa53.png">

This is likely what is happening here.
