### ISSUE TITLE
Suggestion: Use $ to prefix aliases

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#185]
Suggestion by Nick George to distinguish aliases by prefixing with $. This would result in error messages if the alias were not resolved. With this change, if you say "STC" instead of "SCT" then SUSHI won't flag the error, and just put STC in the output.

**Comment by cmoesel** [comment]
After some discussion, we've come to the following proposal:

1. Allow authors to _optionally_ use `$` as the first character in an alias name.
2. Disallow authors from defining other names, ids, or slices with a starting `$`.
3. Add smarter detection for contexts where only a URL/URI makes sense and log an error if there is a non-URL/non-URI string that does _not_ resolve to an aliased URL/URI.

Together, these allow for using `$` aliases as a stylistic preference for those who wish to do so, while also lowering the likelihood of alias typos from propagating without an error.

**Comment by cmoesel** [comment]
I should add:
4. If SUSHI runs into something prefixed w/ `$` and can't resolve it, then it should issue an error.
