### ISSUE TITLE
SUSHI allows authors to put constraints on choices that have been constrained out

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#210]
The following is allowed by SUSHI:
```
Profile: MyProfile
Parent: Observation
* valueCodeableConcept MS
* value[x] only Quantity
```

Ideally, SUSHI should recognize and report this as an error and exclude the `valueCodeableConcept` constraints from the profile's SD.

**Comment by cmoesel** [comment]
Or maybe since we're emitting an error, we leave both constraints in the AT anyway.  Either way, the author needs to correct it.

**Comment by cmoesel** [comment]
I'm guessing that if we did the rules in the reverse order (the `only` rule first) that we *would* get an error as expected.

**Comment by mint-thompson** [comment]
@cmoesel you are correct that when the `only` rule comes first, an error is already being shown. The case where the `only` rule comes later is the one not currently being addressed.
I'm thinking about a case that is similar to the initial example, but one where I don't think an error should be emitted.
```
Profile: MyParentProfile
Parent: Observation
* valueCodeableConcept MS

Profile: MyChildProfile
Parent: MyParentProfile
* value[x] only Quantity
```
The type constraint on `MyChildProfile.value[x]` will effectively eliminate the flag set by the parent, but I don't feel like this is likely to be a mistake, so no error message should be shown. So, it's not enough to say that the error case is "a choice with constraints on it gets constrained out." The requirement is the somewhat stricter "a choice with constraints set by a profile gets constrained out in the same profile."
Does this make sense to folks?

**Comment by cmoesel** [comment]
Makes total sense, @mint-thompson.  Good thinking!
