### ISSUE TITLE
Change to info message (very quick change)

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#214]
Referring to these two info messages:
`info: Building FHIR Implementation Guide...`
`info: Built FHIR Implementation Guide; ready for IG Publisher.`

I think these two messages are confusing -- They imply that SUSHI is building the IG.  Can you change these two messages to say:

`info: Preparing ImplementationGuide resource...`
`info: Built ImplementationGuide resource; ready for IG Publisher`

**Comment by cmoesel** [comment]
I understand the confusion, but it is doing more than building the ImplementationGuide resource.  It is also generating other files when necessary, copying page files, etc.  So the suggested text is also confusing (or at least misleading).

How about:

`info: Assembling Implementation Guide sources...`
`info: Assembled Implementation Guide sources; read for IG Publisher.`

Does that work?

**Comment by markkramerus** [comment]
should be "ready for IG Publisher" not "read", but otherwise, that seems ok.
