### ISSUE TITLE
error: Cannot resolve element from path: contained.Questionnaire.id

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#224]
Trying to create an instance of a contained resource but the path is not found

This should be enough to show how to trigger the error:

Instance:       ACDCExamplePHQ-2QuestionnaireResponse
InstanceOf:     ACDCQuestionnaireResponse
Title:          "IHE ACDC Example Questionnaire for PHQ-2"
* contained.Questionnaire.id = "contained-questionnaire"

**Comment by ngfreiter** [comment]
SUSHI doesn't yet have special support for `contained`. To SUSHI, `contained` is of type `Resource`, so `contained` can only have fields that are on `Resource` itself (`id`, `meta`, `implicitRules`, `language`). So the following could work:
```
Instance: ExampleInstance
InstanceOf: QuestionnaireResponse
Title: "My Example"
* contained.id = "contained-questionnaire"
```
But this might not be in depth enough for your use case. There has been some discussion of possible approaches for handling contained resources here: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/contained.20resources.
