### ISSUE TITLE
Consider changing the way slices are referred to in paths

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#231]
FHIR represents slices with a colon, as follows:
`extension:ReviewedBy`
`component:GeneStudied`
etc.
Why not be consistent with FHIR, and save brackets for numerical indices?
I actually hate to suggest this, but it also came up at the connectathon. 
It would read like this:
```
* extension:ReviewedBy.value[x] only Reference
* extension:ReviewedBy.valueReference only Reference(Practitioner)
```

**Comment by cmoesel** [comment]
We discussed this as an option early on (which you probably remember).  At that time, I think we chose `[` `]` for:
* consistency with CIMPL (which uses `[` `]` for the CIMPL equivalent of slices)
* consistency within FSH (which uses `[` `]` for reference selectors as well)
* ability to use direct URLs when referencing `extension` slices (with `:`, the `:` in URLs makes it a little trickier)
* and we felt that the `[` `]` also made it pop out more when reviewing the text

I'm not saying we shouldn't re-consider (in fact, I think when we discussed it, I originally was in favor of `:` myself) -- I'm just providing some of the historical discussion.

**Comment by ngfreiter** [comment]
@markkramerus and @cmoesel would it be fair to close this issue? Is this something we are still considering? It would be a pretty big shift at this point, and we went to ballot using the `[]`.

**Comment by cmoesel** [comment]
Given that FSH is now ballot for normative w/ the `[` `]` syntax, I think it is safe to close this.
