### ISSUE TITLE
Setting an extension's extension to 0..0 causes spurious error message

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#232]
I believe the following snippet should be legal, but it is generating an error message:
```
Extension:  CarePlanReview
Id: icare-care-plan-review
Description:    "Documentation of a re-assessment of the Care Plan"
* value[x] 0..0
* extension contains  ReviewedBy 0..1
* extension[ReviewedBy].value[x] only Reference
* extension[ReviewedBy].valueReference only Reference(Practitioner)
* extension[ReviewedBy].extension 0..0
```
I'm getting the follow error message, pointing at the final line: 
```
error: No individual slice may have max > max of sliced element, but max of slice undefined (*) > max of sliced element (0).
  File: C:\Users\mkramer\Documents\GitHub\fsh-icare\icare.fsh
```
(If I were to speculate, and I may be way off base, it seems like SUSHI is looking at the sub-extension under the extension that I'm trying to zero out, and for some reason, comparing its max card (*) to the max card of the parent (set to 0).)

**Comment by jafeltra** [comment]
Fixed by PR #245 and will be included in the next release.
