### ISSUE TITLE
Element out of order

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#240]
Mark Kramer reports in a [fsh-mode PR](https://github.com/standardhealth/fsh-mcode/pull/100#issuecomment-587957355) that the IG Publisher is emitting this error:

> http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-tnm-clinical-stage-group	error	The element Observation.valueCodeableConcept is out of order (and maybe others after it)

We should look into this to determine if SUSHI is putting this element in the wrong place.

**Comment by ngfreiter** [comment]
Unable to reproduce this.
