### ISSUE TITLE
sushi --init

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#242]
Once we've more firmly established how IG configuration and folder structure works, we should support something like `sushi --init` to allow users to quickly start a new SUSHI project w/ everything in place and default config values.

**Comment by peturv** [comment]
How would this be performed best do you think? Fetching the contents of a git repo to the destination or including the barebone template in the sushi code?

For my part I think the latter would be preferable since it would insure version compatibility between template and sushi version.

**Comment by cmoesel** [comment]
I was thinking the latter as well.  Once we determine what we want the config and overall structure to look like (we're currently still working that out), I think this task should come pretty easily.

But loading templates from an external GitHub repo is an interesting idea.  I could see us maybe supporting something like that such that the user can provide a GitHub repo name and we'd use that as a template instead.  But I'd say that would be a good bit down the road, as we have plenty to do already!

**Comment by ngfreiter** [comment]
Released https://github.com/FHIR/sushi/releases/tag/v0.15.0
