### ISSUE TITLE
system URIs not being display by CodeAlreadyFixedError

### ISSUE THREAD

**Issue by lawley** [FHIR/sushi#250]
My sushi output is filled with errors like:

`error Cannot fix #snapshot to this element; a different code is already fixed: #snapsot.`

presumably this is because of a mismatch with the CodeSystem URIs, but I cannot debug it from this error message

**Comment by cmoesel** [comment]
This looks to me like you are trying to fix a code called `snapshot` (with an `h`) to an element that is already fixed to the code `snapsot` (without the `h`).

**Comment by cmoesel** [comment]
hi @lawley -- have you had a chance to look into this further and confirm if the issue was really the missing `h`?

**Comment by cmoesel** [comment]
I'm closing this out under the assumption that you've resolved this on your side. Please re-open if you feel there is something that needs to be fixed in SUSHI.
