### ISSUE TITLE
Slices not working on AuditEvent

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#254]
From Keith Boone over on zulip ([link](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/My.20slices.20aren't.20working.20on.20AuditEvent)):

I'm trying to create slices on agent in audit event, where the slices are on the values of role and requestor.

First I set up the discriminators thus:

```
* agent ^slicing.discriminator[0].type = #pattern
* agent ^slicing.discriminator[0].path = "role"
* agent ^slicing.discriminator[1].type = #pattern
* agent ^slicing.discriminator[1].path = "requestor"
* agent ^slicing.description = "Slicing is based on role and requestor."
* agent ^slicing.ordered = false
* agent ^slicing.rules = #open
```

Then I declare use of three slices in the profile:

```
* agent contains Source 1..1 and HumanRequestor 0..* and Destination 1..1
```

Then I describe constraints on each slice inline, including on the discriminator fields:

```
* agent[Source].role = http://dicom.nema.org/resources/ontology/DCM#110153 "Source"
* agent[Source].requestor = false
* agent[Source].altId 1..1
* agent[Source].name 1..1
* agent[HumanRequestor].requestor = true
* agent[HumanRequestor].role 0..*
* agent[HumanRequestor].altId 1..1
* agent[HumanRequestor].name 1..1
* agent[Destination].role = http://dicom.nema.org/resources/ontology/DCM#110152 "Destination"
* agent[Destination].requestor = false
* agent[Destination].altId 1..1
* agent[Destination].name 1..1
```

The produced StructureDefinition doesn't include discriminators for agent at all.

**Comment by keithboone** [comment]
See https://github.com/IHE/ACDC/blob/master/ACDCQueryArtifactAuditEvent.fsh

**Comment by keithboone** [comment]
Found it I think.  The directory structures of the output changed between releases.  So it was getting generated in a different location.

**Comment by cmoesel** [comment]
Ah, yes.  And sorry.  It's fun working with still-developing tools and standards isn't it. ;-)

That particular change (to where things get output) was requested by several members of the community, and it seemed like a better organizational construct, so we figured the earlier we make the change the better.

**Comment by cmoesel** [comment]
Once you've confirmed that's what was happening, please feel free to close this issue.

**Comment by keithboone** [comment]
Consider it closed from my perspective, but either I don't know how to close it, or, more likely, since I didn't open it (you did on my behalf), I don't have permissions.

**Comment by cmoesel** [comment]
Oh right!  I opened it so I guess I have to close it.  Thanks for the confirmation!
