### ISSUE TITLE
With the restucturing of output files, documentation needs to be updated

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#256]
After output files have been restructured, the IG needs to be updated to reflect the new structure.

**Comment by cmoesel** [comment]
Ah, I assume you mean the fhir-shorthand documentation here?
http://build.fhir.org/ig/HL7/fhir-shorthand/sushi.html#executing-sushi-from-command-line

Good catch.  Thank you.

**Comment by keithboone** [comment]
Yeah, I was maybe gonna throw you a pull request in an hour or so.

**Comment by cmoesel** [comment]
Docs have been updated.  Thanks, @keithboone!
