### ISSUE TITLE
Consider some default behavior, such as automatic setting of `short`

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#278]
There are some cases where we may want to consider automatically setting the `short` when certain rules are used.  For example, if an author adds an extension to a profile, perhaps the `short` on that extension element should be the `title` specified in the Extension's SD.

This is a little "smarter" and more opinionated than FSH has been so far, so we should really think about whether or not we want to start doing things like this (or if it should be user-configurable).

Also note, it *seems* that maybe the IG publisher will automatically set the short to the Extension's root element's short if it exists -- so that is another option, but we actually don't need to do anything there if the IG Publisher does it for us.  So perhaps we would only use the title if (a) the Extension definition does not have a root element short defined, and (b) the Extension definition does have a title defined.

**Comment by markkramerus** [comment]
As long as we handle overrides (caret syntax wins over default), then I'm in favor of smart defaults.

**Comment by cmoesel** [comment]
This has been implemented now (in version 1.1 I think?)
