### ISSUE TITLE
Consider adding RuleSets anywhere within a list of rules

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#279]
Since rules can be order-dependent, consider the possibility of inserting rule sets at arbitrary points in a set of rules, by simply stating the rule set name, as follows:

```
Profile: XYZ
* rule-XYZ-1
* rule-set-1
* rule-XYZ-2
* rule-set-2
* rule-XYZ-3
etc.
```

**Comment by cmoesel** [comment]
I'd actually prefer to have a keyword that makes it more explicit:
```
Profile: XYZ
* rule-XYZ-1
* apply rule-set-1
* rule-XYZ-2
* apply rule-set-2
* rule-XYZ-3
```
I think this is clearer to the user and it gives the parser something easier to key off of than just an arbitrary name with no keywords.
