### ISSUE TITLE
Path-history parameter missing from IG resource

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#286]
The IG Publisher will give a warning if the path-history parameters is not set. For mCODE, it should look like this:
```
    },
    "parameter": [
      {
        "code": "copyrightyear",
        "value": "2019+"
      },
      {
        "code": "releaselabel",
        "value": "STU1"
      },
      {
        "code": "show-inherited-invariants",
        "value": "false"
      },
      {
        "code": "path-history",
        "value": "http://hl7.org/fhir/us/mcode/history.html"
      }
    ]
  }
```

**Comment by cmoesel** [comment]
We need to determine if we support this now or wait until we implement the new approach to configuration.  A few not-quite-random thoughts:
* I think the path-history is only required for official HL7 IGs, so we should probably try to determine if it is an HL7 IG before applying it
* I think maybe there is a formula for how to construct the history URL, so hopefully we can build it based on the canonical
