### ISSUE TITLE
Sushi writes local folder name with \

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#299]
I start MY ig.ini in ig-data with:
template= #ig-template

Sushi writes ig.ini as
template= \#ig-template

Build fails on IG Builder (I have a workaround for my local build).

**Comment by keithboone** [comment]
Bang!  Shooting them down faster than I can find them...

**Comment by keithboone** [comment]
This still doesn't work in most recent release that I ran.
This is what I have in: fsh\ig-data\ig.ini
[IG]
template = #ig-template
usage-stats-opt-out = false
copyrightyear = 2020+
license = CC-BY-4.0
version = 0.1.0
ballotstatus = CI Build
fhirspec = http://build.fhir.org/

This is what Sushi writes out:
[IG]
ig = input/ImplementationGuide-ainq.fhir.us.saner.json
template = \#ig-template
usage-stats-opt-out = false
copyrightyear = 2020+
license = CC-BY-4.0
version = 0.1.0
ballotstatus = CI Build
fhirspec = http://build.fhir.org/

**Comment by keithboone** [comment]
I can either make the CI build work and disable sushi, or make sushi work and break the CI build, but I cannot do both.

**Comment by cmoesel** [comment]
@keithboone -- is this a different issue now?  Based on above it looks like the template value is correct.  Are you saying that `ig = input/ImplementationGuide-ainq.fhir.us.saner.json` is a problem now?

**Comment by keithboone** [comment]
No, I corrected it.  The \ didn't show up, I needed to double it in the markdown.

**Comment by cmoesel** [comment]
I just cloned your repo and ran SUSHI 0.11.1 against it and the resulting ig.ini file was correct (no extra `\`).  Have you tried it locally (after updating to SUSHI 0.11.1)?  It seems to me that maybe the IG Auto Builder is not using the latest greatest SUSHI.  I'll ping @jmandel about that.

**Comment by keithboone** [comment]
NM:  Found it,
it was the difference between 
npm install fsh-sushi 
and 
npm install **-g** fsh-sushi

I was still a version behind after running the first command.
