### ISSUE TITLE
Way to define inline extensions does not match the specification

### ISSUE THREAD

**Issue by jduteau** [FHIR/sushi#303]
Defining an inline extension is supposed to work like this according to the specification:

* extension contains
      ombCategory 0..5 MS
      detailed 0..*
      text 1..1 MS

  // constraints to define the inline extensions would follow, e.g.:
* extension[ombCategory] only Coding
* extension[ombCategory].valueCoding from http://hl7.org/fhir/us/core/ValueSet/omb-race-category (required)
* extension[text] only string
  // etc...

When I tried that, it didn't work.  Instead I had to use the following:
* extension contains availableFlag 1..1 MS 
* extension contains document 0..* MS
* extension[availableFlag].value[x] only boolean
* extension[document].value[x] only Attachment

**Comment by cmoesel** [comment]
Thanks for reporting this.  As you figured out, you have to include the `value[x]` when constraining the value of an extension.  And you need to use keyword `and` in the contains.  So... the doc _should_ read like this:
```
* extension contains
    ombCategory 0..5 MS and
    detailed 0..* and
    text 1..1 MS
// constraints to define the inline extensions would follow, e.g.:
* extension[ombCategory].value[x] only Coding
* extension[ombCategory].valueCoding from http://hl7.org/fhir/us/core/ValueSet/omb-race-category (required)
* extension[text].value[x] only string
// etc...
```

And you should be able to simplify yours to:
```
* extension contains availableFlag 1..1 MS and document 0..* MS
* extension[availableFlag].value[x] only boolean
* extension[document].value[x] only Attachment
```

**Comment by markkramerus** [comment]
I'll fix this in the doc. Thanks for catching the bug.

**Comment by markkramerus** [comment]
Published and closing
