### ISSUE TITLE
Publisher values incorrect for contact and publisher

### ISSUE THREAD

**Issue by Gjoll** [FHIR/sushi#320]
^ contact and
^ publisher 
dont appear correctly in published IG.

If I define the following:

RuleSet: Header
  * ^contact[0].telecom.system = http://hl7.org/fhir/contact-point-system#url
  * ^contact[0].telecom.value = "http://www.hl7.org/Special/committees/cic"
  * ^date = "2019-11-01"
  * ^status = http://hl7.org/fhir/ValueSet/publication-status#draft
  * ^publisher = "Hl7-Clinical Interoperability Council"
  * ^version = "0.0.2"

Profile:    BreastRadiologyReport
Parent:     DiagnosticReport
Id:         breastRadiologyReport
Title:      "Breast Radiology Report"
Mixins: 	Header

and run sushi I get an IG. If I look at the output structure definitions all the items appear to be set correctly.

If I look at the html pages, the publisher and contact fields are, *literally, fishy*.

This is from the web page, json tab. Note
a) publisher 'James Tuna".
b) contact 'Bill Cod'

  "url" : "http://example.org/fhir/fish/StructureDefinition/breastRadiologyReport",
  "version" : "0.1.0",
  "name" : "BreastRadiologyReport",
  "title" : "Breast Radiology Report",
  "status" : "draft",
  "date" : "2019-11-01T00:00:00-05:00",
  "publisher" : "James Tuna",
  "contact" : [
    {
      "name" : "Bill Cod",
      "telecom" : [
        {
          "system" : "email",
          "value" : "cod@reef.gov"
        }
      ]
    }
  ],

Maybe some test cod, err, I mean code, got left in here?

:-)

**Comment by cmoesel** [comment]
Hi @Gjoll -- check your `package.json`.  I'm guessing that Mr. Tuna and Mr. Cod are set as `author` and `maintainer` in there.  That's what gets used to set the overall publisher and contacts for the IG.

**Comment by Gjoll** [comment]
Yep, that was it. Changed the package.json and the problem was fixed.
Sorry, I should have caught that...
The fishy smell was not coming from your side :-)
