### ISSUE TITLE
Syntax for code

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#321]
I'd love it if this syntax could be supported for some constraints:
* status = #complete | #pending

This would make my life so much simpler, as I could skip crafting a value set.

**Comment by cmoesel** [comment]
I think the difficulty here is that FHIR doesn't have a good mechanism for allowing a choice of two values without using a value set -- so supporting this without a value set would require changes to FHIR itself (unless there is some other way I'm not aware of).

If we wanted to support this without changes in FHIR, I think the best we could do would be to create a value set on the fly for the author, using some convention to determine how that value set is named.  Is that something you would like us to consider?  Or is that too much magic?

**Comment by ngfreiter** [comment]
@keithboone, any thoughts on this? This would be a change to the FSH syntax itself, so I think if this is still a desired feature, it should go on the FSH ballot.

**Comment by keithboone** [comment]
Added to ballot comments.

**Comment by cmoesel** [comment]
Closing as this was discussed as part of ballot resolution and we couldn't find a clear path to a solution.
