### ISSUE TITLE
I really wish I could just say subject only Patient and not have to remember to say subject only Reference(Patient)

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#322]
I really wish I could just say 
* subject only Patient 

and not have to remember to say 
* subject only Reference(Patient)

There's only a few places where you might even be able to do both, but I cannot honestly think of one.  Even in Parameters you can tell by name: value[X] vs. resource

**Comment by cmoesel** [comment]
Hi @keithboone.  I hope you are signed up for the FHIR Shorthand ballot in May.  If so, and if you remember, please file a formal comment on this -- as it is a change request for the syntax itself.

Of course, if you don't get that comment in there, we'll still consider it.  That's just a good way to have it formally considered.

**Comment by keithboone** [comment]
Added to ballot comments.

**Comment by cmoesel** [comment]
Closing as this was discussed as part of the ballot process and decided against.
