### ISSUE TITLE
Allow Mixins to refer to other Mixins

### ISSUE THREAD

**Issue by Gjoll** [FHIR/sushi#323]
Currently a mixin can not reference another mixin. I would request that Sushi be modified to allow mixins to refer to other mixins.
A circular reference would obviously trigger a sushi run time error.

ie

Ruleset: ladedah
Mixins: yadda1, yadda2, yadda3

Ruleset: yadda1
Mixins: yadda11
* .....

Ruleset: yadda11
* .....

Ruleset: yadda2
* .....

Ruleset: yadda3
* .....

**Comment by cmoesel** [comment]
This was implemented when we switched from `Mixins` to `insert` rules.
