### ISSUE TITLE
Forcing input from user during _upgradePublisher.sh breaks CI

### ISSUE THREAD

**Issue by peturv** [FHIR/sushi#327]
Hiya!

Tried running my automated pipeline after having it dormant for some time and realized that confirmation is now required before download in  _updatePublisher.sh

https://github.com/FHIR/sushi/blob/7d6163f5a75ae3ba14981a892df626a3c5cdfc6d/src/ig/files/_updatePublisher.sh#L41

It would be nice to be able to pass a flag to force the answer to the question.
Submitting a PR for this (only for the .sh as I don't have a PC to try out a .bat version)

**Comment by ngfreiter** [comment]
Closing since #328 and #354 addressed this.
