### ISSUE TITLE
Building bundle with resources has order dependent behavior in build

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#333]
If you try to write the Bundle first, then the included resources (in the same file), the FHIR build fails, but if invert the order, the build succeeds.

Sushi should order the resources based on their dependencies.

The build probably shouldn't break with a report about trying to generate the same resource twice during validation phase either, but that would probably be related to IG Builder

**Comment by cmoesel** [comment]
Hi @keithboone -- thanks for reporting.  I've confirmed and we'll work on a fix.

For whoever picks this up, I used these test cases:

This *works*:
```
Instance: MyBundledPatient
InstanceOf: Patient
* active = true
* name[0].given[0] = "John"
* name[0].family = "Doe"

Instance: MyBundle
InstanceOf: Bundle
* type = #collection
* entry[0].resource = MyBundledPatient
```

This *does not work*:
```
Instance: MyBundle
InstanceOf: Bundle
* type = #collection
* entry[0].resource = MyBundledPatient

Instance: MyBundledPatient
InstanceOf: Patient
* active = true
* name[0].given[0] = "John"
* name[0].family = "Doe"
```

I compared the SUSHI output on each and it looks like for the second case (the not working on), we are adding `MyBundledPatient` to the resource list in the IG JSON twice:
```
      {
        "reference": {
          "reference": "Patient/MyBundledPatient"
        },
        "name": "MyBundledPatient",
        "exampleBoolean": true
      },
      {
        "reference": {
          "reference": "Patient/MyBundledPatient"
        },
        "name": "MyBundledPatient",
        "exampleBoolean": true
      },
```

This probably means that instance is being generated twice (but only when we reference it before we define it) and put into our export `Package` twice.
