### ISSUE TITLE
request module is deprecated

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#344]
When installing SUSHI, this message is displayed:
```
$ npm install -g fsh-sushi
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/sushi -> /usr/local/lib/node_modules/fsh-sushi/dist/app.js
```

While this is probably not a big deal, it may be concerning to users.  We should remove the dependency on request by using built-in node libraries or replacing it with another module.

**Comment by fungiboletus** [comment]
I would recommend `got`.

**Comment by cmoesel** [comment]
Thanks for your suggestion, @fungiboletus.  We agree that `got` would be an excellent choice, but we're actually planning a client-side version of SUSHI (that runs in your browser), so we decided to use `axios` since it is also browser-ready.

**Comment by cmoesel** [comment]
(BTW -- the client side SUSHI is to support something like a "playground" where you can try SUSHI in your browser).

**Comment by davidhay25** [comment]
The browser usage looks interesting - any more details?

**Comment by cmoesel** [comment]
We haven't started work on it yet, but the idea is to provide a quick and easy way for people to experiment with FSH.  Imagine a web page with a big text box on the left-hand side.  You type FHIR Shorthand into the box, and click a button (or maybe not?) and you see the resulting FHIR profile(s) on the right-hand side of the page.  It's a zero-install super quick way to try something out.

It might also have other features of benefit such as permalinks -- so you can save the FSH you entered as a permalink and then post that link somewhere.  When people follow the link, they see the FSH you wrote in the web page (as well as its corresponding results).  I imagine this could be helpful for reporting bugs or asking questions on Zulip.

**Comment by bkaney** [comment]
FWIW although it was last year, we went through the options for FHIR Kit Client and landed on [cross-fetch](https://github.com/lquixada/cross-fetch) based on the smaller and cleaner codebase and uncertainty with the future of axios.  Cross-fetch works on the server, in the browswer, react native, and ionic.

**Comment by cmoesel** [comment]
Thanks @bkaney -- we already integrated axios at this point, but it's such a small part of SUSHI, I'm sure we can easily replace it if axios becomes any trouble.  If so, we'll keep cross-fetch in mind!

**Comment by davidhay25** [comment]
@cmoesel - certainly sounds interesting! Let me know if you want an early beta tester.
