### ISSUE TITLE
Replace FSH names with URLs in contexts that make sense

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#355]
If someone has a ValueSet called `MyVS`, and in some context they reference it as follows:
```
* valueCanonical = MyVS
```
it seems like SUSHI should be smart enough to recognize that we want to insert the canonical URL of MyVS, and not the string "MyVS". This would effectively allow FSH names to act as aliases for their canonical URL in contexts that make sense. This type of usage isn't documented in the FSH spec, so if we were to add this feature, we would need to update that as well.

**Comment by lawley** [comment]
You would need to be careful about how and when the replacement included (or not) the version along with the URI in the canonical

**Comment by cmoesel** [comment]
Relevant zulip conversation: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Setting.20canonical.20values

**Comment by jafeltra** [comment]
The `Canonical()` keyword can now be used for assigning canonical URLs by name. To assign the canonical in the example above, you can do the following:

```
* valueCanonical = Canonical(MyVS)
```
