### ISSUE TITLE
New grammar to support min and max bindings

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#371]
To support min and max bindings, could Shorthand support grammar like this?
```
* foo from MyMinValueSet (min)
* foo from MyPreferredValueSet (preferred)
* foo from MyMaxValueSet (max)
```

See original thread: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Defining.20a.20Max.20binding.3F

**Comment by cmoesel** [comment]
I think the question here is whether or not min/max VS are used enough to warrant adding them as a 1st-class feature of FSH. For some reason, FHIR has chosen not to support them as 1st-class properties -- so why should FSH? That's an honest question, with no negative connotation intended.

If they are not commonly used, including them in FSH may just make things more complicated/confusing for the 95% (???) of authors who don't use them -- as now you need to understand not only the differences between the normative bindings, but also the min/max bindings and understand which binding flavors can be applied concurrently and which ones cancel out previous values... Again, not arguing against it, but trying to think of the implications of adding these to FSH grammar (as every feature you add to the grammar, by definition, increases the grammar's complexity).

**Comment by cmoesel** [comment]
Additional conversation in the thread linked above led to the following recommendation from Grahame Grieve: 

> for now, you shouldn't make it easier. When we add multiple bindings in R5, then FSH should follow along. cause then we'll know what it looks like.

Since R5 is going to address this, we should probably wait until then so that we don't end up doing it in a way that won't meld well with R5 in the future.  Until then, using the standard extensions should work fine.

**Comment by cmoesel** [comment]
Closing in favor of #1165.
