### ISSUE TITLE
How to create Profile (not extension)

### ISSUE THREAD

**Issue by bwalsh** [FHIR/sushi#382]
Hi.  Thanks for a great project.
I've been successful at creating extensions, but wondering how to create a new, standalone profile.

FooBar.fsh
```
Profile:        FooBar
Parent:         Element
Id:             foo-bar
Title:          "FooBar"
Description:    "An attempt to create a simple object"
* key only string
* value only string
```

produces
```
error No element found at path key for FooBar, skipping rule
  File: /src/FooBar.fsh
  Line: 6
error No element found at path value for FooBar, skipping rule
  File: /src/FooBar.fsh
  Line: 7
```

In the reference, the keywords section is defined, but there is no guidance on how to create rules?

https://build.fhir.org/ig/HL7/fhir-shorthand/reference.html#defining-profiles

**Comment by cmoesel** [comment]
Profiles are constraints on existing FHIR resources or datatypes.  While there are [several rules about profiles](http://hl7.org/fhir/R4/profiling.html#limitations), one of them is:
> Profiles cannot give more specific names to elements defined in the base specification, or add new elements

If you look at the [definition of Element](http://hl7.org/fhir/R4/element.html), it only defines two elements: `id` and `extension`.  This why attempting to put constraints on elements called `key` and `value` fail in your example above.

It sounds like you may really want to create [logical models](http://hl7.org/fhir/R4/structuredefinition.html#logical) (note: the anchor for that link is a little off, so you need to scroll down).  If so, this is a feature not yet defined in FHIR Shorthand (see [future considerations](https://build.fhir.org/ig/HL7/fhir-shorthand/index.html#future-considerations)) or supported in SUSHI.

**Comment by bwalsh** [comment]
@cmoesel  thanks very much for the quick answer.  much appreciated.
