### ISSUE TITLE
Sushi doesn't like primitives with extensions but no value as a valid instance of the primitive when counting required quantities

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#393]
This example demonstrates the problem:

Profile: MeasureReportProfile
Parent: MeasureReport
* group.population.count 1..1
* group.population.code 1..1

Instance: SampleMeasureReport
InstanceOf: MeasureReportProfile
* status = #complete
* type = #summary
* measure = "fake"
* period.start = "2020-04-26"
* period.end = "2020-04-26"
* group[0].population.count = 1
* group[0].population.code.coding = http://terminology.hl7.org/CodeSystem/measure-population#measure-population

// The following doesn't get counted as an instance of count, I suspect because in json, this is recorded
// in the _count property since count is a primitive.
* group[0].population[1].count.extension.url = "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
* group[0].population[1].count.extension.valueCode = http://terminology.hl7.org/CodeSystem/data-absent-reason#unsupported

// This, on the other hand, does work, but NOTE that code is CodeableConcept, and so doesn't do the _code weirdness
* group[0].population[1].code.extension.url = "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
* group[0].population[1].code.extension.valueCode = http://terminology.hl7.org/CodeSystem/data-absent-reason#unsupported

If you run just this file, it will barf with:
error Element MeasureReport.group.population.count has minimum cardinality 1 but occurs 0 time(s).
  File: C:\Users\kboone\eclipse-workspace\test\fsh\MissingIntegerTest.fsh
  Line: 6 - 19

But clearly that isn't true.  There really is a count.  Unfortunately, sushi doesn't see it b/c the extension is stored in _count, not in count is a primitive, and primitives have to work another way because "reasons".

**Comment by keithboone** [comment]
[MissingIntegerTest.fsh.txt](https://github.com/FHIR/sushi/files/4534820/MissingIntegerTest.fsh.txt)

**Comment by keithboone** [comment]
Or at least I think that's what's not working here.

**Comment by keithboone** [comment]
This is where I think things are broken in InstanceExporter.js.  NOTE: I'm a node novice, but not a JavaScript novice.  I THINK I understand what is going wrong here, but cannot figure out how to get this running in the Eclipse debugger to work out the details.


validateRequiredChildElements(instance, element, fshDefinition) {
        // Get only direct children of the element
        const children = element.children(true);
        children.forEach(child => {
            // Get the last part of the path, A.B.C => C
            const childPathEnd = child.path.split('.').slice(-1)[0];
            let instanceChild = instance[childPathEnd];
            // If the element is a choice, we will fail to find it, we need to use the choice name
            if (instanceChild == null && childPathEnd.endsWith('[x]')) {
                const choiceSlices = children.filter(c => c.path === child.path && c.sliceName);
                for (const choiceSlice of choiceSlices) {
                    instanceChild = instance[choiceSlice.sliceName];
                    if (instanceChild != null) {
                        break;
                    }
                }
            }
            /************* BEGIN KWB Edits **************/
            // AT THIS STAGE, instanceChild should be a child matching childPathEnd
            // BUT, if instanceChild can be a primitive (detectable if it's type starts with a lowercase leter)
            // AND the value is still null,
            // Then you need to look for it using '_' + childPathEnd
            // Then you can do the rest of the stuff afterwards
            if (instanceChild == null && isPrimitive(child.type)) {
            	instanceChild = instance['_' + childPathEnd];
            }
            /************* END KWB Edits **************/
            
            // Recursively validate children of the current element
            if (Array.isArray(instanceChild)) {
                // Filter so that if the child is a slice, we only count relevant slices
                instanceChild = instanceChild.filter((arrayEl) => { var _a; return !child.sliceName || ((_a = arrayEl) === null || _a === void 0 ? void 0 : _a._sliceName) === child.sliceName; });
                instanceChild.forEach((arrayEl) => {
                    if (arrayEl != null)
                        this.validateRequiredChildElements(arrayEl, child, fshDefinition);
                });
            }
            else if (instanceChild != null) {
                this.validateRequiredChildElements(instanceChild, child, fshDefinition);
            }
            // Log an error if:
            // 1 - The child element is 1.., but not on the instance
            // 2 - The child element is n..m, but it has k < n elements
            if ((child.min > 0 && instanceChild == null) ||
                (Array.isArray(instanceChild) && instanceChild.length < child.min)) {
                // Can't point to any specific rule, so give sourceInfo of entire instance
                utils_1.logger.error(`Element ${child.id} has minimum cardinality ${child.min} but occurs ${instanceChild ? instanceChild.length : 0} time(s).`, fshDefinition.sourceInfo);
            }
        });
    }

**Comment by ngfreiter** [comment]
Thanks for the detailed report! I agree with what you're thinking. Looks like when the primitive itself does not have a value, but children of the primitive do have values, SUSHI does not correctly account for this by looking for the relevant `_<property>` element as well. I will add this to our backlog to fix.

**Comment by bkaney** [comment]
Here is another example where the primitive has a value, but similar error as described.

```
% npx sushi -version                                                                        
v0.12.6
```

```
Extension: QuestionnaireName
* value[x] only string

Profile: MyQuestionnaireResponseProfile
Parent: QuestionnaireResponse
* questionnaire.extension contains QuestionnaireName named questionnaireName 1..1

Instance: MyQuestionnaireResponse
InstanceOf: MyQuestionnaireResponseProfile
* status = #completed
* questionnaire = "http://fhir.org/Questionnaire/1"
* questionnaire.extension[questionnaireName].valueString = "foo"
```

Output:
```
error Element QuestionnaireResponse.questionnaire.extension has minimum cardinality 1 but occurs 0 time(s).
  File: /test-fsh/example.fsh
  Line: 8 - 12
error Element QuestionnaireResponse.questionnaire.extension:questionnaireName has minimum cardinality 1 but occurs 0 time(s).
  File: /test-fsh/example.fsh
  Line: 8 - 12
```
But the instance seems to be okay:
```
{
  "resourceType": "QuestionnaireResponse",
  "id": "MyQuestionnaireResponseWithQuestionnaire",
  "meta": {
    "profile": [
      "http://localhost/test/StructureDefinition/MyQuestionnaireResponseProfile"
    ]
  },
  "_questionnaire": {
    "extension": [
      {
        "url": "http://localhost/test/StructureDefinition/QuestionnaireName",
        "valueString": "foo"
      }
    ]
  },
  "status": "completed",
  "questionnaire": "http://fhir.org/Questionnaire/1"
}
```

**Comment by cmoesel** [comment]
Thanks for the additional information, @bkaney.  I'm hoping that maybe this is one of the bugs we can work on during the Connectathon (if there is enough downtime to work on bugs).
