### ISSUE TITLE
Sushi is generating arrays for Reference.identifier

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#394]
Sushi lets me do this to MeasureReport:

* subject.identifier 1..*
* subject.identifier ^short = "The subject shall have at least one identifier which uniquely identifies the subject to the recepient."
* subject.identifier ^comment = "Requiring subject.identifier allows reports to be queried by locations using a well-known identifier."

And then in instances, creates an array for subject.identifier.

But subject.identifier in the base is 0..1

It should barf at me trying to extend beyond cardinality of 1 for subject.identifier

**Comment by ngfreiter** [comment]
Huh, it looks like this actually isn't `Reference.identifier` specific either. It looks like if an element has cardinality `x..1`, and there's a rule to constrain it to `y..*`, SUSHI isn't catching that. I'm amazed that hid from us for this long, we will definitely want to fix this, thanks for reporting!
