### ISSUE TITLE
SUSHI exports choice specializations incorrectly

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#447]
`Observation.value[x]` allows the following choices: `Quantity`, `CodeableConcept`, `string`, `boolean`, `integer`, `Range`, `Ratio`, `SampledData`, `time`, `dateTime`, `Period`.

FSH allows authors to say this:
```
* value[x] only Duration
```

Duration is a *specialization* (not a *profile*) of `Quantity`.  This is something like a concrete subclass relationship.  Unlike profiles, specializations are in fact a distinct *type* in the FHIR type system.  SUSHI currently exports the rule above like so:
```json
{
  "id": "Observation.value[x]",
  "path": "Observation.value[x]",
  "type": [ { "code": "Duration" } ]
}
```

When I first implemented it, the above worked.  IG Publisher did not complain and it rendered `value[x]` as expected. (At least that's how I remember it).  I assumed it was legal.

It appears, however, that it is not actually legal and now the IG Publisher complains:
> illegal constrained type Duration from Quantity, CodeableConcept, string, boolean, integer, Range, Ratio, SampledData, time, dateTime, Period in http://hl7.org/fhir/StructureDefinition/Observation

The only proper way to support this is via a FHIRPath.  SUSHI needs to do one of the following.  Either:

* generate and insert an invariant using the valid FHIRPath to represent the constraint (in which case it will need to generate a unique constraint id)
* log an error and provide the user detailed guidance on how to add the invariant to their FSH

The first is more user friendly, but might do some unexpected things for unsuspecting users.  The second requires action from the user, but they become aware of the issue and also have control over its precise details (e.g., they can use an invariant id consistent w/ other invariant ids in their IG).

We also need to decide if we are going to further shield the user by allowing them to use the path `valueDuration` in rules even though it really should be `valueQuantity`.  I think we probably need to enforce `valueQuantity` because if they constrained a quantity to `Duration or Age`, it would not be valid to specify different constraints on `valueDuration` and `valueAge` at the same time.

**Comment by cmoesel** [comment]
See: https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Narrow.20Quantity.20to.20Duration.20and.20Age

**Comment by ngfreiter** [comment]
Oh the GitHub magic doesn't work
