### ISSUE TITLE
Incorrect cardinality from contains rule

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#450]
See https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/slice.20cardinalities.

When using the contains, the more standard usage is to do:
```
* focus contains foo 1..1 and bar 1..*
```
However, a user should also be able to break the contains into separate lines:
```
* focus contains foo 1..1
* focus contains bar 1..*
```
However, in the second case, the cardinality of the `bar` slice does not get added to the differential, causing the IG Publisher to incorrectly assume that the `bar` slice has the same cardinality as the original `focus` element, which is `0..*`.

**Comment by ngfreiter** [comment]
I think this is probably happening because the first `contains` rule sets the cardinality of the `foo` slice to `1..1`, which implicitly sets the cardinality of the `focus` array to `1..*`. Then when the second slice is added, it is added with cardinality `1..*`, which to SUSHI looks like it matches the cardinality of the `focus` element. So to SUSHI, the cardinality of the slice appears to be the same as the cardinality of the overall array, so nothing is added to the differential.

Disclaimer that the above is just a guess.

**Comment by cmoesel** [comment]
Wow.  I think that's a really good guess!  If we have code in there that only writes the card to the slice if it is different than the base, then we probably should remove that and always write to the slice.  If it turns out to be redundant, there's really no harm there.
