### ISSUE TITLE
Only rule fails with Profile of Reference

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#451]
This issue is best explained through an example:
```
Extension: ReferencePeriod
Title: "Reference Period"
Id: reference-period
* value[x] only Period

Profile: ReferenceWithPeriod
Parent: Reference
Title: "Reference with Period"
Id: reference-with-period
* extension contains ReferencePeriod named period 1..1

Extension: FixedStartReference
Title: "FixedStartReference"
Id: fixed-start-reference
* value[x] only ReferenceWithPeriod
* valueReference.extension[period].valuePeriod.start = "2020-01-01"
```
Everything shown above should be valid. We create an extension and a profile on Reference that uses that extension. We then try to use our profile on Reference, and access the elements of that extension. However, the last line shown causes an error:
```
No element found at path valueReference.extension[period].valuePeriod.start for FixedStartReference, skipping rule
```

But, we can recreate this example using some other datatype like HumanName instead of Reference:
```
Extension: NamePeriod
Title: "Name Period"
Id: name-period
* value[x] only Period

Profile: NameWithPeriod
Parent: HumanName
Title: "Name with Period"
Id: name-with-period
* extension contains NamePeriod named period 1..1

Extension: FixedStartName
Title: "FixedStartName"
Id: fixed-start-name
* value[x] only NameWithPeriod
* valueHumanName.extension[period].valuePeriod.start = "2020-01-01"
```
and everything seems to work fine. There are no errors logged. If you look at the output for the `value[x]` element on the `fixed-start-reference` vs the `fixed-start-name`, you will see that on the `fixed-start-reference`, the type is:
```
"type": [
          {
            "code": "Reference",
            "targetProfile": [
              "http://example.org/fhir/fish/StructureDefinition/reference-with-period"
            ]
          }
        ]
```
while on the `fixed-start-name`, the type is:
```
 "type": [
          {
            "code": "HumanName",
            "profile": [
              "http://example.org/fhir/fish/StructureDefinition/name-with-period"
            ]
          }
        ]
```
On the Reference, the type is given by `targetProfile`. This seems to be the issue at the root of this bug. The `targetProfile` is used to indicate the profile for the target of a Reference, but here it is being used to indicate the profile on the Reference itself. As a result, the Profile is not correctly unfolded and we fail to find the elements.

**Comment by cmoesel** [comment]
On a `Reference`, `targetProfile` should only be used to indicate what the reference _points to_.  If the intent is to profile the `Reference` datatype itself, then the profile URL needs to go in `profile`, not `targetProfile`.

**Comment by cmoesel** [comment]
It seems there are two possible solutions here:

1. Only use `targetProfile` if the `only` type is `Reference(Something)`
2. Check if the `only` type is a profile on `Reference`; and if so, use `profile`, otherwise use `targetProfile`.

While #2 is a little more "magic"y, I think it's likely what users would prefer.  I know users have asked us if we can relax the grammar to not require them to say `Reference(...)` when the target is obviously a `Reference`.

BTW -- I'm a little surprised that SUSHI didn't complain that the profile `reference-with-period` was not a valid target for the reference.
