### ISSUE TITLE
Documentation about specification of version of resources

### ISSUE THREAD

**Issue by danka74** [FHIR/sushi#474]
How to supply the version of e.g. a CodeSystem should be documented.
Thanks,
Daniel

**Comment by cmoesel** [comment]
Hi @danka74 -- thanks for the suggestion.  We'll make a note to add a description of this to the spec.  It will likely mention that the version is inherited from the overall version of the IG, but if you wish to override the version for a specific resource (profile, extension, code system, etc) you can do so via `* ^version = "1.2.3"`.

**Comment by danka74** [comment]
I need to clarify the need: when specifying CodeSystem version in a FilterComponent the way to specify the version should be documented!
See: https://github.com/FHIR/sushi/issues/473#issuecomment-637811324

**Comment by cmoesel** [comment]
Oh!  Right!  Somehow I totally forgot that whole conversation. Thanks!

**Comment by cmoesel** [comment]
I believe these are better documented now in the version of FSH currently being balloted.
