### ISSUE TITLE
SUSHI hangs when duplicate file names in pagecontent

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#477]
This comes from this thread on zulip: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Issues.20with.20latest.20beta.

It does indeed seem to be the case that SUSHI hangs when two files in data/input/pagecontent have the same name but different extensions. I recreated this by adding `test.md` and `test.xml` to my pagecontent folder. Although the zulip thread is specifically about the config branch, I observed this hanging on `config-yaml` and `master`.

I don't know exactly what is causing the hang, but it seems to be coming from this bit of code:
https://github.com/FHIR/sushi/blob/b6631db57a8c5c94522094eaacd93292d69f76aa/src/ig/IGExporter.ts#L355-L370

**Comment by cmoesel** [comment]
Oh.  I like the GitHub code preview.  Nice!  So I think I see the issue in the code.  If there are duplicates in `pageData`, then `mightHaveDuplicates` gets set to `true` on line 361.  At line 370, we loop back to `while (mightHaveDuplicates)`, which is now `true`.  Although it resets it to `false` on line 357, nothing in `pageData` has actually changed, so of course we're going to come out the other side with `mightHaveDuplicates === true` again.  And repeat the loop.  Again.  And again.  And again.
