### ISSUE TITLE
Remove extra metadata from generated profiles

### ISSUE THREAD

**Issue by costateixeira** [FHIR/sushi#499]
when sushi generates a structureDef, there is some content that is imported from the original StructureDef but I don't think is part of the structureDef (for example mappings). Is this needed? I think this should not be there by default, but if it is there by default, how to remove it?

**Comment by cmoesel** [comment]
Hi @costateixeira.  It's not 100% clear how much of a base resource needs to be carried over and reflected in the profile.  We'll reach out on chat.fhir.org to try to get some additional guidance on this and act accordingly.

**Comment by cmoesel** [comment]
See: https://chat.fhir.org/#narrow/stream/179177-conformance/topic/What.20of.20Base.20Resources.20should.20be.20carried.20over.20to.20Profiles

**Comment by cmoesel** [comment]
Based on discussion in Zulip (above), we will leave most metadata properties intact.  But we will update our logic to be more specific about it's removal of extensions on StructureDefinitions (using [FHIR-27535](https://jira.hl7.org/browse/FHIR-27535) as a guide).

**Comment by jafeltra** [comment]
Addressed in #534
