### ISSUE TITLE
Trouble w/ instances of Parameters

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#504]
A user on Zulip has reported an issue using this FSH:

```
Instance: ParametersEx12
InstanceOf: Parameters
Usage: #inline
* parameter.name = "patient"
* parameter.valueReference = Reference(PatientEx12)
```

In this case, they receive the error:
```
error: Cannot read property 'forEach' of undefined.
```
The reporter says `PatientEx12` and `ParametersEx12` are both inline instances in a bundle.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/valueReference.20for.20Parameters

**Comment by cmoesel** [comment]
If I had to guess, I suspect that SUSHI is trying to enumerate the reference type targets to see what are the allowed reference targets -- but maybe the reference doesn't list the targets since it basically supports all targets. But that's just a guess.  We need to look into it.

**Comment by ngfreiter** [comment]
One extra thing to note is that the error does not occur with just the FSH posted above. The `PatientEx12` also does have to be defined:
```
Instance: ParametersEx12
InstanceOf: Parameters
Usage: #inline
* parameter.name = "patient"
* parameter.valueReference = Reference(PatientEx12)

Instance: PatientEx12
InstanceOf: Patient
Usage: #inline
* gender = #F
```
