### ISSUE TITLE
Changing URLs break extension support

### ISSUE THREAD

**Issue by palfrey** [FHIR/sushi#532]
#407 fixed URL support for code systems and valuesets, and the code seems to indicate that it would do the same for extensions. However I'm still seeing errors.

Example FSH:
```
Extension: TestExtension
* ^url = "http://foo.bar.baz"

Profile: TestProfile
Parent: Communication
* payload.extension contains TestExtension named ContentConcept 1..
// * payload.extension contains http://foo.bar.baz named ContentConcept 1..
* payload.extension[ContentConcept].value[x] only CodeableConcept
```

gets me `error No element found at path payload.extension[ContentConcept].value[x] for TestProfile, skipping rule`. Switching it out for the commented line gets me `Cannot create ContentConcept extension; unable to locate extension definition for: http://foo.bar.baz.` instead.

Any thoughts? I need the URL to be a particular value for historical reasons with an existing data set.

**Comment by cmoesel** [comment]
Hi @palfrey -- I agree, this _looks_ like it should work (both the uncommented and commented code should each work).  We'll take a look at it.

**Comment by palfrey** [comment]
Awesome. Just tested the fixes locally, and fixes my original issue. Thanks!
