### ISSUE TITLE
"Accessing non-existent property 'INVALID_ALT_NUMBER'" warning

### ISSUE THREAD

**Issue by palfrey** [FHIR/sushi#551]
Every time I run sushi I get the following warning twice.

`(node:39554) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency`

I don't think it's caused any issues, but looks like it should be at least looked at. Upstream bug is https://github.com/antlr/antlr4/issues/2834

**Comment by cmoesel** [comment]
Hi @palfrey -- thanks for reporting this.  We especially appreciate the link to the upstream bug report! We'll keep an eye on that report and upgrade ANTLR once a new version is released.

BTW -- we're currently targeting Node LTS versions, so if you want the most well tested experience of SUSHI, I'd recommend Node 12.x for now...

**Comment by cmoesel** [comment]
This is no longer an issue since SUSHI now requires Node 18.
