### ISSUE TITLE
IG Publisher context determined by directory name (undocumented)

### ISSUE THREAD

**Issue by TrueWill** [FHIR/sushi#555]
I found this _very_ confusing in v0.15. I'd recommend at least documenting it if not removing it entirely.

I was getting a message of
> Current FSH tank conforms to an IG Publisher context. Output will be adjusted accordingly.

and no _gen... scripts were created.

I finally looked at the source:

```ts
// If a fsh subdirectory is used, we are in an IG Publisher context
const isIgPubContext = path.parse(input).base === 'fsh';
```

It appears that if you specify an ~~`--out`~~ (correction: input) directory named 'fsh' then the program behaves differently.

Please consider addressing this confusion. Thank you!

**Comment by cmoesel** [comment]
This behavior is necessary to support the IG Publisher integration, particularly for use with the HL7 IG Auto Build process.  That said, we definitely _could_ provide a more helpful / detailed message to try to reduce confusion.  Do you think something like this would be sufficient?

> SUSHI detected a "fsh" directory in the input path. As a result, SUSHI will operate in "IG Publisher integration" mode.  This means:
> - the "fsh" directory will be used as the input path
> - the parent of the "fsh" directory (e.g., "../fsh") will be used as the output path
> - generation of publisher-related scripts will be suppressed (i.e., assumed to be managed by you) 

(BTW -- this IG Publisher integration is still in flux; we hope that in the future we'll have an overall approach that is easier to use and understand).

**Comment by TrueWill** [comment]
@cmoesel That seems very reasonable; thank you! 😄
