### ISSUE TITLE
SUSHI-GENERATED-FILES should be changed to .html or .txt

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#571]
There is no reason that this file should be .md, and that file extension just makes it hard to open. At least on Windows, there is no application designated as default to open markdown files. Opening should be as easy as double clicking. Please change to .txt or .html

**Comment by cmoesel** [comment]
SUSHI 1.0.0 no longer produces this file (when using the SUSHI 1.0.0 project layout, so I'm closing this issue as OBE.
