### ISSUE TITLE
SUSHI should warn when invalid files are detected

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#594]
When SUSHI detects an invalid file in a directory like `fsh/ig-data/input/examples`, it emits an error saying:
```
error Invalid file detected in directory fsh/ig-data/input/examples. Input FHIR definitions must be JSON.
```
In this case, an error is likely too strong. SUSHI should just continue processing with a warning so that the publishing process can move forward.

**Comment by cmoesel** [comment]
I think this has been overcome by events.  With the new approach that uses `input/fsh` and no `ig-data` folder, I don't think this is a problem anymore.  @ngfreiter - would you agree?

**Comment by ngfreiter** [comment]
Yep, agreed!
