### ISSUE TITLE
Cannot fix meta.profile[0] value to a canonical

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#601]
The following rule:
```
* meta.profile[0] = Canonical(MyObservation)
```
results in the following error:
```
Sushi: error No element found at path meta.profile[0] for SpecializedObservation, skipping rule (00:04.0512)
```

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Accessing.20meta.20attributes

**Comment by ngfreiter** [comment]
I'm not sure this is a bug. See this explanation here: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Accessing.20meta.20attributes/near/210253782. Let me know if you agree @cmoesel.

**Comment by cmoesel** [comment]
@ngfreiter -- why must you be so insolent? ;-)

Yes, of course, you're right.  My head was in the wrong place.  Thanks for putting it straight.
