### ISSUE TITLE
Cannot easily specify "unit" on Quantity

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#652]
We support an easy syntax for specifying a Quantity when the units are taken from UCUM:
```
* valueQuantity = 155.0 '[lb_av]'
```
But there is no way to specify the `unit` field when doing this. It might make sense to support a syntax like:
```
* valueQuantity = 155.0 '[lb_av]' "lb"
```
where the `valueQuantity.unit` would then get set to "lb". The `unit` is meant to be a human readable value, and there is plenty of precedent for setting human readable values as strings at the end of assignments, so I don't think users would find this a confusing addition.

This came out of a conversation with @markkramerus on creating an instance of the [bodyweight](https://www.hl7.org/fhir/bodyweight.html) profile, which does require the `unit` keyword. Wanted to put this out here for discussion, and if we think this is a good idea, I'll add it to the backlog for SUSHI and to JIRA for an update to the FSH spec.

**Comment by cmoesel** [comment]
👍

**Comment by ngfreiter** [comment]
Alright, added an issue for FSH to update the syntax: https://jira.hl7.org/browse/FHIR-29635, and added this to our backlog.
