### ISSUE TITLE
Quantity Units in Instance

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#695]
The following FSH:
```
* valueQuantity.unit = "lb"
* valueQuantity = 155 '[lb_av]'
```
results in no text string in `valueQuantity.unit`.  I think this is a bug, because the second statement doesn't imply clearing out the unit. In the second statement, since the unit is optional. In other words, if you write
```
* valueQuantity = 155 '[lb_av]' "lb"
```
then you would replace whatever is in `valueQuantity.unit` with "lb" but if no text is given, it doesn't mean remove `valueQuantity.unit`.

Note that this occurred in an instance.

**Comment by cmoesel** [comment]
This would effectively mean that `=` isn't really _assignment_; it is _merge_.  I feel like this is a topic that warrants further discussion, because, as a developer `=` meaning to _merge_ a complex object feels very weird to me.

**Comment by cmoesel** [comment]
After discussion among the team, we've agreed that `=` should represent full assignment (not multi-part or merge assignment), so this is not a bug.
