### ISSUE TITLE
SUSHI Documentation bad URL

### ISSUE THREAD

**Issue by fransdelrio** [FHIR/sushi#738]
After  **_sushi --init_**  command, interactive tool shows a message with an incorrect SUSHI Documentation's URL.

Screenshot: 
![sushi-docs-bad-url](https://user-images.githubusercontent.com/8531620/105723516-a3a66b80-5f05-11eb-8cbc-04b9e765e38b.png)

When the correct SUSHI Docs URL is:  [https://fshschool.org/docs/sushi/](https://fshschool.org/docs/sushi/)

**Comment by cmoesel** [comment]
Oops.  Thanks!
