### ISSUE TITLE
SUSHI should support `Canonical` for relevant Instances too

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#743]
SUSHI should support the `Canonical(...)` lookup for instances w/ a canonical URL too.  This is not just _Conformance_ and _Terminology_ resources, but also things like `Questionnaire`.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Failed.20canonical.20lookup

**Comment by costateixeira** [comment]
I think I encountered the same issue, also in a questionnaire, so I'd like to +1 this.

**Comment by shovanroy-github** [comment]
I'm also facing the same issue with Questionnaire instance reference from QuestionnaireResponse. +1 from me as well.

**Comment by cmoesel** [comment]
We'll put this near the top of our list for our next sprint.  In the mean time, you *should* be able to just set the canonical as a string (e.g. `"http://myig.org/Questionnaire/123"`).  I realize it's not as convenient as using the `Canonical(...)` mechanism, but I just want to be sure you recognize it as a workaround.
