### ISSUE TITLE
Extra extensions in instances

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#759]
In some cases, two FSH rules that should be modifying the same extension are actually creating and modifying *different* extensions.  See [this test case](https://fshschool.org/FSHOnline/#/share/2Zhcys3):

```
Profile: TestMoney
Parent: Money
* value 1..1 MS 
* currency 1..1
* currency = #EUR

Extension: TestExtension
* extension contains money 1..1 and test 0..1
* extension[money].value[x] only TestMoney
* extension[money].value[x] 1..1
* extension[test].value[x] only string

Profile: TestProfile
Parent: Observation
* extension contains TestExtension named test 1..1

Instance: TestObs
InstanceOf: TestProfile
* status = #final
* code = #testcode
* extension[TestExtension].extension[money].valueMoney.value = 10
* extension[TestExtension].extension[money].valueMoney.currency = #EUR
```

The `TestObs` instance should have a single `TestExtension` extension with a single `money` sub-extension w/ value `10` and currency `#EUR`.  Instead, we end up with two `TestExtension` extensions, one with only the `currency` set and another with both `currency` and `value` set:
```json
{
  "resourceType": "Observation",
  "id": "TestObs",
  "meta": {
    "profile": [
      "http://example.org/StructureDefinition/TestProfile"
    ]
  },
  "extension": [
    {
      "url": "http://example.org/StructureDefinition/TestExtension",
      "extension": [
        {
          "url": "money",
          "valueMoney": {
            "currency": "EUR"
          }
        }
      ]
    },
    {
      "extension": [
        {
          "valueMoney": {
            "currency": "EUR",
            "value": 10
          },
          "url": "money"
        }
      ],
      "url": "http://example.org/StructureDefinition/TestExtension"
    }
  ],
  "status": "final",
  "code": {
    "coding": [
      {
        "code": "testcode"
      }
    ]
  }
}
```

Discovered while trying to reproduce a different bug in [this zulip thread](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/value.5Bx.5D.20confusion.20on.20Instances/near/226386860).

**Comment by cmoesel** [comment]
@ngfreiter and I have discussed this and noted that it seems to be due to the use of `extension[TestExtension]` (referring to the name of the extension) rather than `extension[test]` (referring to the name of the slice).  In brief, SUSHI recognizes the former as a request to create a `TestExtension` extension, but does not recognize it as a conforming instance of the `test` slice.  As a result, SUSHI generates an extension containing the fixed values of the `test` slice (since the slice is `1..1`) -- but then creates another instance of the extension to satisfy the `extension[TestExtension]` rules.

Extensions are the only case where a slice can potentially be referenced by something other than the slicename, so I think it would make sense if SUSHI recognized that `extension[TestExtension]` is, in fact, an instance of the extension with slicename `test`.  It could do this by getting the canonical URL of `TestExtension` (which it already needs to do) and checking if it matched the fixed URL of any of the existing slices.  If so, that is the element it should target.  This would result in the intended behavior 99.9% of the time, and in rare cases where it is not the intended behavior, authors can use other, more explicit, approaches to get the results they want.

**Comment by mj-h** [comment]
I was just about to prepare an issue for the following behavior ([FSH Online](https://fshschool.org/FSHOnline/#/share/3jRrKW1)):, but I think this is covered by your issue and your analysis, @cmoesel : 

```
Profile: MyProfile
Parent: Patient
// This serializes correctly:
* ^extension[MyBooleanExtension].valueBoolean = true

Profile: ChildProfile
Parent: MyProfile
// This leads to a duplicate extension-array entry
* ^extension[MyBooleanExtension].valueBoolean = false

Extension: MyBooleanExtension
* value[x] only boolean
```
I'm not sure if the use-case I'm presenting is good practice in FHIR, but I noticed that the output contains a duplicate entry in the extension array: 
```
...
{
  "extension": [
    ...
    {
      "url": "http://example.org/StructureDefinition/MyBooleanExtension"
      "valueBoolean": true
    }, {
      "url": "http://example.org/StructureDefinition/MyBooleanExtension"
      "valueBoolean": false
    }
  ]
}
```

**Comment by cmoesel** [comment]
This is slightly different than what I described above, since the extension is not included in a profile -- and therefore there is no associated "sliceName" for it -- but in principal, I think the problem is the same.  If you say `^extension[MyBooleanExtension]` and we find an extension instance w/ the canonical URL of `MyBooleanExtension`, we should use that instead of creating a new one.

Thanks for providing another ever-so-slightly use case for this!

**Comment by mj-h** [comment]
I think I found [another example](https://fshschool.org/FSHOnline/#/share/3vWPmhN), where this bug still pops up:

```
Profile: MyProfile
Parent: Patient
// This serializes correctly:
* name ^extension[MyBooleanExtension].valueBoolean = true

Profile: ChildProfile
Parent: MyProfile
// This leads to a duplicate extension-array entry
* name ^extension[MyBooleanExtension].valueBoolean = false

Extension: MyBooleanExtension
* value[x] only boolean
```

**Comment by cmoesel** [comment]
Oh no.... Thanks for reporting!

**Comment by mj-h** [comment]
I have to make a small correction: Even the Parent-profile is not serialized correctly in this example. In other words, the following lines are sufficient to trigger the bug:

```
Profile: MyProfile
Parent: Patient
// This does not serialize correctly
* name ^extension[MyBooleanExtension].valueBoolean = true


Extension: MyBooleanExtension
* value[x] only boolean
```

Some random context just in case you are wondering why we are putting extensions into the StructureDefinitions of our profiles:  The standard FHIR validation does not allow cross-instance-validation. For example, it does not allow implementing the rule "No two Patients must have the same name". We are adding such additional constraints as extensions to the StructureDefinitions, so that our custom validation-tool can be implemented as a small add-on to standard FHIR validation tools.
