### ISSUE TITLE
SUSHI does not recursively read input files

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#786]
If the user has a folder structure like:
```
input
- fsh
    - fsh-file1.fsh
- resources
    - structuredefinitions
        - file1.json
    - codesystems
    - valuesets
```
Then SUSHI does not recursively read in `file1.json` as a predefined resource. This should probably be supported.

**Comment by cmoesel** [comment]
Note that unless things changed, there is a limitation in what the IG Publisher will and won't accept.  According to [this thread](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/sushi.3A.20input.20folder.20recurse), the files must be one of these:
* `resources/{ResourceType}-{id}.json`
* `resources/{ResourceType}/{id}.json`
(also allowing for `.xml`)

So if we implement this, we can be more flexible than that, but perhaps we should notice when someone violates this and flag it as a warning.  (But first let's confirm that the IG Publisher really is that strict, just in case it has recently loosened up).
