### ISSUE TITLE
Filter operator "in" can have a code value

### ISSUE THREAD

**Issue by danka74** [FHIR/sushi#812]
As described here:
https://www.hl7.org/fhir/snomedct.html#4.3.1.0.8.2
the filter operator can take a concept as a value, not just a string.

https://github.com/FHIR/sushi/blob/d785865cf9d84e89316b0abec9ff2c9671fd5871/src/import/FSHImporter.ts#L1853

**Comment by cmoesel** [comment]
Yes, I agree, we need to be more lenient here based on your link above and the FHIR spec definition here: http://hl7.org/fhir/R4/valueset-definitions.html#ValueSet.compose.include.filter.value
