### ISSUE TITLE
SUSHI Runs Forever on FSH Example

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#827]
We include this example of a Capability Statement in the FSH IG:

https://github.com/HL7/fhir-shorthand/blob/master/input/images/CapabilityStatementTemplate.fsh

SUSHI 1.3.2 starts compiling and never* completes. It is a massive instance but it still shouldn't be this bad. It is probably the same efficiency problem we have seen on big bundle profiles with many slices. 

I also tried this on 2.0.0B1 and the results were not different.

*I killed it after about 20 minutes.

**Comment by alex-vg** [comment]
Your link is presenting me a 404.
