### ISSUE TITLE
SSL Error behind Proxy

### ISSUE THREAD

**Issue by alex-vg** [FHIR/sushi#835]
I get some SSL errors when I `sushi -i`. Using a corporate proxy.
`error Unable to download _genonce.sh from http://raw.githubusercontent.com/HL7/ig-publisher-scripts/main/_genonce.sh: write EPROTO 24168:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:....deps\openssl\openssl\ssl\record\ssl3_record.c:332:`

Any workaround?

**Comment by cmoesel** [comment]
I have not seen this issue before.  Is it possible that your corporate proxy also re-signs SSL certificates?  If so, you may need to add your corporate certificates to the chain.  In Node, you can do this via a special `NODE_EXTRA_CA_CERTS` environment variable.

See: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

_NOTE: If you just need the scripts, you can download them directly from the [ig-publisher-scripts](https://github.com/HL7/ig-publisher-scripts) repo.  Easiest way is probably to download the repo zip: https://github.com/HL7/ig-publisher-scripts/archive/refs/heads/main.zip

**Comment by cmoesel** [comment]
@alex-vg Have you been able to resolve this?  Can we close this issue?

**Comment by alex-vg** [comment]
Resolved temporarily by downloading the files manually. 
Error still exists. It could be a problem in the used axios version. Updating axios dependency could resolve it.

**Comment by cmoesel** [comment]
Hmmm... [According to npm](https://www.npmjs.com/package/axios), axios 0.21.1 is the latest, and we've had that [in our package.json](https://github.com/FHIR/sushi/blob/master/package.json#L82) for about 7 months.  So there's nothing to upgrade to regarding axios.  Is it possible you might need to upgrade your local installation of openSSL?

**Comment by alex-vg** [comment]
That's it. I was using an older (14.3) node.js version on windows that was bundled with an older openssl. Thank you!
