### ISSUE TITLE
batch files online check not working behind proxy

### ISSUE THREAD

**Issue by alex-vg** [FHIR/sushi#836]
There is a little showstopper in all batch files. It tries to check the online connection via ping.
`PING tx.fhir.org -4 -n 1 -w 1000 | FINDSTR TTL && GOTO isonline`
Which fails behind proxies, but the script can still operate normal.

I've only testet this on Windows.

Workaround for me is to remove the online check.

Edit: _genonce.bat is not working with the check removed. It fails to download things.

**Comment by cmoesel** [comment]
These batch files are not created or maintained by the SUSHI team.  We download them from the [ig-publisher-scripts](https://github.com/HL7/ig-publisher-scripts) repository.  I'd recommend reporting issues there so that the script maintainers can help you.
