### ISSUE TITLE
Parent USCorePatientProfile not found 

### ISSUE THREAD

**Issue by lindenquan** [FHIR/sushi#850]
According to the document, Parent could be id, name or url. I tried to use us-core patient profile as parent whose name is "USCorePatientProfile", id is "us-core-patient", url is "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient". But none of them worked. The error message says " Parent USCorePatientProfile not found"

**Comment by cmoesel** [comment]
If you wish to reference definitions from US Core, you need to configure the US Core IG as a dependency of your IG. You can find an example of this in the FSH School SUSHI Configuration documentation: https://fshschool.org/docs/sushi/configuration/#recommended-configuration

**Comment by lindenquan** [comment]
Thanks, after adding US Core dependency. It works now.
