### ISSUE TITLE
SUSHI tried to find FHIR 4.1.0 as R5 (instead of R4B)

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#851]
See https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/how.20to.20indicate.20version.204b.20.3F/near/243357349

**Comment by cmoesel** [comment]
Note, the final R4B will be 4.3.0, so we should account for that as well.

**Comment by ngfreiter** [comment]
Fixed by #860.
