### ISSUE TITLE
Support Profiles of Logical Models

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#857]
We were under the impression that you cannot have a profile on a logical model (e.g., cannot have `"kind": "logical"` and `"derivation: constraint"`) -- but [it seems that maybe you can](https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Type.20on.20First.20Element.20in.20Differential.20for.20Logical.20Models/near/243972570).

**Comment by ngfreiter** [comment]
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Fixed.20Values.20in.20Logical.20Models
