### ISSUE TITLE
SUSHI doesn't correctly parse codes whose system has a fragment

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#873]
```
* code = http://some.sdo.org/CodeSystems.html#systemABC#1234
```
produces JSON with:
```json
{
  "code": "systemABC#1234",
  "system": "http://some.sdo.org/CodeSystems.html"
}
```
but it should be:
```json
{
  "code": "1234",
  "system": "http://some.sdo.org/CodeSystems.html#systemABC"
}
```

Note that we do need to support `#` in codes too, however.  In that case, the code should be wrapped in `""`.  So we need to support this as well:
```
* code = http://some.sdo.org/CodeSystems.html#"systemABC#1234"
```
(which *should* result in the first JSON object above).

See: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Using.20DICOM's.20FHIR.20value.20sets/near/245465153

**Comment by jafeltra** [comment]
After investigating this issue in #883, we came to the conclusion that support for this actually already present. We should be using the `\` character to escape the `#` as part of a system. Therefore, the FSH

```
* code = http://some.sdo.org/CodeSystems.html\#systemABC#1234
```

can be used to produce the desired JSON:

```
{
  "code": "1234",
  "system": "http://some.sdo.org/CodeSystems.html#systemABC"
}
```
which is also demonstrated in [FSH Online here](https://fshschool.org/FSHOnline/#/share/2WrFShn).

As mentioned, the `""` can be used to support `#` in codes, as [shown here](https://fshschool.org/FSHOnline/#/share/3l0mzFY).
