### ISSUE TITLE
SUSHI 2.0.0 Beta 2: "The first index in a Soft Indexing sequence must be "+", an actual index of "0" has been assumed" although the first index is '+'

### ISSUE THREAD

**Issue by ylboerner** [FHIR/sushi#879]
While using SUSHI 2.0.0 Beta 2 I receive the error "The first index in a Soft Indexing sequence must be "+", an actual index of "0" has been assumed" although the first index is designated as '+'. This happens if using soft indexing **on extensions** like this:

```
* extension[+].url = "testurl"
* extension[=].valueString = "{variable}"
```

SUSHI 2.0.0 Beta 1 and SUSHI stable run through just fine though!

**Comment by ngfreiter** [comment]
@ylboerner Is there some more context around the error? I've tried to recreate it with this FSH:
```
Instance: P
InstanceOf: Patient
* extension[+].url = "testurl"
* extension[=].valueString = "test"
```
and I don't get an error, so there could be some surrounding FSH that is playing a part in the error.

**Comment by ylboerner** [comment]
@ngfreiter In our case, this is the exact segment producing the error: 

```
RuleSet: assertExpression (expression, fehlermeldung, warningOnly)
* test[=].action[+].assert
  * label = "Regel"
  * description = "Ist die Regel '{expression}' erfüllt?"
  * expression = "{expression}"
  * warningOnly = {warningOnly}
  * extension[+].url = "omitted"
  * extension[=].valueString = "{fehlermeldung}"
```

and used like this in a TestScript Definition: 

```
* insert assertExpression (entry.resource.count(\)>0, 'Es wurden keine Suchergebnisse gefunden', false)
```

Error message:

```
error The first index in a Soft Indexing sequence must be "+", an actual index of "0" has been assumed
  File: /Users/y/Repositories/Testing/TestScripts/FSH-TestScripts/input/fsh/static_content/ruleset.fsh
  Line: 92
  Applied in File: /Users/y/Repositories/Testing/TestScripts/FSH-TestScripts/input/fsh/test01.fsh
  Applied on Line: 82
```

Both snippets are from different files. Is there anything else I can provide you with? I'd be delighted to help solving this.

**Comment by cmoesel** [comment]
Hi @ylboerner -- I see this in your ruleset:
```
* test[=].action[+].assert
```

Is it possible the error is referring to the `test[=]` part of the path?  If you have not established an index for `test` before you `insert` the ruleset, then `test[=]` will not work.  There must be a path that has `test[+]`, `test[0]`, or `test[n]` (for some value of _n_) before you can insert a ruleset that starts with a reference `test[=]`.

**Comment by patrick-werner** [comment]
hi @cmoesel, checked and tested that, it wasn't the cause of the problem. Sushi seems to loose track of the extension index inside of a ruleset.  
I extracted an "minimalistic" example FSH file to be able to reproduce the issue:
https://fshschool.org/FSHOnline/#/share/3mrMjf4

**Comment by ngfreiter** [comment]
Yeah this is definitely a bug. I'm working on a fix right now, but in the meantime, you should be able to work around this by using indentation to set the elements of `extension`. See this FSHOnline: https://fshschool.org/FSHOnline/#/share/3zceKkQ for an example.
