### ISSUE TITLE
SUSHI should support tab character for indentation

### ISSUE THREAD

**Issue by ngfreiter** [FHIR/sushi#902]
SUSHI currently does not support using tabs to indent paths. We should consider adding support for indentation using tabs, where a tab character is treated the same as two space characters. See [this thread](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/SUSHI.202.2E0.2E0.20.3A.20Indenting.20with.20tab.20.3F) for more details.

**Comment by jafeltra** [comment]
This would require a spec change, and those changes should be proposed through the ballot process for the FSH Spec.
