### ISSUE TITLE
Instances not correctly written to ImplementationGuide JSON

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#92]
The references to instances in the generated ImplementationGuide.json is incorrect.  For example, I have a project with an instance of Patient.  When I run sushi to generate an IG, I find this in the generated ImplementationGuide JSON:

```json
        {
        "reference": {
          "reference": "Patient/undefined"
        },
        "name": "Patient-undefined",
        "exampleBoolean": true
      }
```

I've attached a sample project that displays this issue using the version of SUSHI on `master`.

[simple-ig.zip](https://github.com/FHIR/sushi/files/4065357/simple-ig.zip)

**Comment by kjmahalingam** [comment]
Fixed in 0.6.0
