### ISSUE TITLE
SUSHI should include inherited constraints from base in the diff of slices

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#932]
Right now, when SUSHI creates a slice, it calls `captureOriginal` on the new slice so that the diff only contains things that are different from the base.  Because of the way that the validator works, however, we must repeat constraints from the base in the slice differential.  I think the easiest way to do this is to _not_ call `captureOriginal` when we create the new slice -- but instead use the same captured original as the base (but someone should confirm).  This means we still would not include things that were constrained on the base _after_ the slice was created, but I think that's probably an OK compromise in order to reduce complexity.

See: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/How.20to.20slice.20on.20the.20value.20of.20an.20extension/near/257451464

**Comment by jafeltra** [comment]
This was partially addressed in #955, and it has not been reported as an issue recently.
