### ISSUE TITLE
Element names with underscores are handled inconsistently

### ISSUE THREAD

**Issue by emesar** [FHIR/sushi#950]
### Background
I'm defining a logical model (`Logical`) in FSH. One of the elements looks like this:
```fsh
* _source 1..1 code "A value representing the source of the data captured within this record"
```
When I run SUSHI, this shows up correctly in the corresponding StructureDefinition:
```json
      {
        "id": "my-logical-model._source",
        "path": "my-logical-model._source",
        "short": "A value representing the source of the data captured within this record",
        "definition": "A value representing the source of the data captured within this record",
        "min": 1,
        "max": "1",
        "type": [
          {
            "code": "code"
          }
        ]
      },
```
However, when I profile the logical model:
```fsh
* _source MS
```
The corresponding StructureDefinition changes the `_` to a `-`:
```json
      {
        "id": "my-logical-model.-source",
        "path": "my-logical-model.-source",
        "mustSupport": true
      },
```
Per [community discussion](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Underscore.20vs.2E.20Dash) on this topic, [underscores are not allowed](https://www.hl7.org/fhir/datatypes.html#id) in elements of the `id` data type.

### Proposed Change

1. SUSHI should handle underscores consistently in both `Logical` and `Profile` definitions.
2. SUSHI should produce a warning when an underscore is used in an element name, rather than silently changing this to a dash.

**Comment by mint-thompson** [comment]
It looks like whatever was causing SUSHI to convert underscores to dashes in element names is no longer occurring. So, element names are consistent across `Logical` and `Profile` definitions. As for the second proposed change, underscores are permitted in element names, so there is no need to produce a warning.
