### ISSUE TITLE
Add warnings for things the IG publisher squawks about

### ISSUE THREAD

**Issue by saulakravitz** [FHIR/sushi#959]
Motivation:   A lot faster  edit-compile-debug loop using sushi than sushi+IGPublisher, and typically more usable messages.

Some examples: Publisher now warns
 - when a codesystem doesn't define the caseSensitive flag. (perhaps Sushi should have a default value for this and always emit it?)
  - when an instance doesn't include a description
  
  Maybe Sushi could have a 'strict' or 'lint' mode where these types of warnings are dispensed?

**Comment by jafeltra** [comment]
Unfortunately, trying to keep in complete alignment with the IG Publisher will be difficult because it changes often. If there are specific cases SUSHI can add better error/warning handling, we can track those as new, individual issues.
