### ISSUE TITLE
SUSHI API cannot find new resources defined in FHIR R5 (4.6.0)

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#970]
David Hay reports:
> Getting an error when using the API with R5 (fhirVersion = 4.6.0) and new resource types (eg Ingredient). The API returns an error "Unknown resource type". It works fine when running locally using a fshTank (ie folder) ...

https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/R5.20and.20the.20API

**Comment by davidhay25** [comment]
Actually the error is not in sushi after all - rather it is in the Lantana serialization library - https://github.com/lantanagroup/FHIR.js

Looks like I need to load the definition files

Feel free to close this issue!

**Comment by cmoesel** [comment]
Thanks for reporting back, @davidhay25.  I'm glad it wasn't SUSHI! ;-)
