### ISSUE TITLE
Cannot assign Location value: X. Value does not match element type: Resource

### ISSUE THREAD

**Issue by citizenrich** [FHIR/sushi#977]
I'm seeing a new error where Sushi complains "Cannot assign Location value: X. Value does not match element type: Resource". This worked in previous versions. Is there a bit more info on how to debug?

**Comment by citizenrich** [comment]
Solved. What was happening was that there was a Library resource called Location which apparently confused Sushi. Once I renamed the Library resource then actual Location resources were referenced properly.

**Comment by cmoesel** [comment]
Ah, yes.  If you have a local definition that matches the name of an external (FHIR) resource or datatype, then when you reference it by name (e.g., `Location`), SUSHI will use your locally defined version.  To use the external version instead, you need to refer to it by its full canonical URL (e.g., `http://hl7.org/fhir/StructureDefinition/Location`).
