### ISSUE TITLE
Questionnaire items with reference extensions parsed incorrectly

### ISSUE THREAD

**Issue by djehring** [FHIR/sushi#984]
When defining an extension on a questionnaire item of type reference and then using it with more than one item the generated resource contains the wrong reference in the first item and no reference in the second one 

Sample fish file:
Extension: DemoSubform
Title: "Extension to provide reference for subform"
Description: "Extension to provide reference for subform"
* value[x] only Reference

Profile: DemoQuestionnaire
Parent: Questionnaire
* ^publisher = "Black Pear Software Ltd"
* item.type = #group //
* item.item.item.item 0..0 
* item.item.extension contains DemoSubform named subform 0..1 MS

Instance: QDemoBug
InstanceOf: DemoQuestionnaire
* status = #draft
* experimental = true
* item[+].text = "Patient and GP details"
* item[=].linkId = "0507770F_B174_4DF4_AB9D_FCF684CC8C8B"
* item[=].item[+].linkId = "LNK-Q-28A3142C-E4A2-470B-B6CC-C87461FB2DA3"
* item[=].item[=].text = "Patient details"
* item[=].item[=].type = #display
* item[=].item[=].repeats = false
* item[=].item.extension[subform].valueReference = Reference(Q-PATIENT-REF)
* item[=].item[+].linkId = "LNK-Q-E3438E09-6C09-4D58-9285-5F9545DB885C"
* item[=].item[=].text = "GP details"
* item[=].item[=].type = #display
* item[=].item[=].repeats = false
* item[=].item.extension[subform].valueReference = Reference(Q-GP-REF)

outputs:
{
  "resourceType": "Questionnaire",
  "id": "QDemoBug",
  "meta": {
    "profile": [
      "https://core.blackpear.com/ig/view/StructureDefinition/DemoQuestionnaire"
    ]
  },
  "item": [
    {
      "type": "group",
      "item": [
        {
          "extension": [
            {
              "url": "https://core.blackpear.com/ig/view/StructureDefinition/DemoSubform",
              "valueReference": {
                "reference": "Q-GP-REF"
              }
            }
          ],
          "linkId": "LNK-Q-28A3142C-E4A2-470B-B6CC-C87461FB2DA3",
          "text": "Patient details",
          "type": "display",
          "repeats": false
        },
        {
          "linkId": "LNK-Q-E3438E09-6C09-4D58-9285-5F9545DB885C",
          "text": "GP details",
          "type": "display",
          "repeats": false
        }
      ],
      "text": "Patient and GP details",
      "linkId": "0507770F_B174_4DF4_AB9D_FCF684CC8C8B"
    }
  ],
  "status": "draft",
  "experimental": true
}

**Comment by cmoesel** [comment]
Hi @djehring.  There is actually a small error in your FSH file that causes this.  Here is how you set the first reference:
```
item[=].item.extension[subform].valueReference = Reference(Q-PATIENT-REF)
```
and then you set the second reference like this:
```
item[=].item.extension[subform].valueReference = Reference(Q-GP-REF)
```

The problem in both cases is that the second `item` in the path is missing the `[=]`.  You have only `item` (without the `[=]`).  According to FSH spec, a path without an indexer will be treated as index `0`.  So in both cases, you are actually setting `item[=].item[0]`. If you change them to this:
```
item[=].item[=].extension[subform].valueReference = Reference(Q-PATIENT-REF)
```
and this:
```
item[=].item[=].extension[subform].valueReference = Reference(Q-GP-REF)
```
then you'll get what you expect.

I've created an example on FSH Online for you here: https://fshschool.org/FSHOnline/#/share/3IPXffp

**Comment by djehring** [comment]
Many thanks. Schoolboy error, couldn't spot that missing syntax for looking....
