### ISSUE TITLE
What and where is "local FHIR cache"?

### ISSUE THREAD

**Issue by MacL3an** [FHIR/sushi#989]
Hi!

Cross posting from Zulip here. Would be happy to help out updating the official docs if someone points me in the right direction.

So I'm trying to run SUSHI where I create a profile using FSH that is based on another custom profile to which I have the JSON file. I'm reading the docs and it mentions something about a "local FHIR cache", where I'm suspecting I'm supposed to be able to put dependencies, but the docs aren't very exhaustive on this. Is there any more info on this topic somewhere? Where is this cache located? How does it work? What kinds of files does it accept?

**Comment by cmoesel** [comment]
Copying in my answer from [chat.fhir.org](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Local.20FHIR.20cache.3F):

> The answer to your question depends on where your custom profile comes from and where it should go.
> 
> If your custom profile comes from another IG / package, then you should declare that package as a dependency of your SUSHI project.  When you do that, SUSHI will download the dependency package and should be able to find the custom profile in it.
> 
> If your custom profile does not belong to another package, then you need to include it in your IG.  If you drop it into one of the supported resource folders in your project (like `input/resources`), then SUSHI will pick it up and you should be able to reference it.

**Comment by MacL3an** [comment]
Thanks for taking the time to reply! For future readers, there is more info in Zulip.
